### ISSUE TITLE
Is it possible to create mesh based on tilemap and gameObjects at the same time?

### ISSUE THREAD

**Issue by Gambolico** [h8man/NavMeshPlus#100]
Right now I have 2 tilemaps (Base and Walls), and some gameObjects that I instantiatiate from a json file at startup.

I have managed to create the NavMeshSurface with the NavMeshCollectSources2d and to pathfind around walls, and also to update the surface with Surface2D.UpdateNavMesh(Surface2D.navMeshData), but I haven't managed to add holes for the gameObjects.

NavMesh object with NavMeshSurface and NavMeshCollectSources2d:

![image](https://user-images.githubusercontent.com/43265816/202739353-eb1addd1-775a-43c9-ae48-0d5fafefc2f0.png)

I have also tried to place a 3D plane and adding the NavMeshObstacle to the gameObjects, but it looks like its making 2 separate instances instead of one:

![image](https://user-images.githubusercontent.com/43265816/202739045-047d1e3a-8342-40c0-86bf-68b3cbdfa6e8.png)

At runtime the agent doesnt care about the tilemap NavMesh anymore.

Is there any way to update the tilemap NavMesh adding the gameObjects as non-walkable?

Keep up the good work!

**Comment by decea89** [comment]
Yes. I do it by this way:

1-Instantiate the gameobject, which must have a SpriteRenderer  and a
NavMeshModifier component (set overriding as a non walkable)
2-Bake again the navmesh

**Comment by decea89** [comment]
check this to know how to bake at runtime

https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#bake-at-runtime

**Comment by h8man** [comment]
@Gambolico 

Sorry, I didn't get a question. So I will try to quest what you want)
- Is it possible to create mesh based on tilemap and gameObjects at the same time?
- yes, [SampleSceneIsometric.unity](https://github.com/h8man/RedHotSweetPepper/blob/master/Assets/Scenes/SampleSceneIsometric.unity) has sprites as a bridge

- Is there any way to update the tilemap NavMesh adding the gameObjects as non-walkable?
- yes, [SampleSceneRuntime.unity](https://github.com/h8man/RedHotSweetPepper/blob/master/Assets/Scenes/SampleSceneRuntime.unity) this scene have runtime obstacle

Ask questions for more details

**Comment by Gambolico** [comment]
@h8man 

My question was the first one, sorry for my bad english.

Im going to look up what you sent me and I'll come right back, thank you.

**Comment by Gambolico** [comment]
@decea89 already had it like that, but doesnt seem to take account of the gameObjects

**Comment by h8man** [comment]
I'm very sorry, the scene with sprites is [SampleSceneDiagonals.unity](https://github.com/h8man/RedHotSweetPepper/blob/master/Assets/Scenes/SampleSceneDiagonals.unity)

it does what you asking, add bridge from sprites on top of tilemap.
Here, I made one sprite element un-walkable as a "chest"
Maybe you need to place it under the same root (I don't recall how root collection works right now)
![image](https://user-images.githubusercontent.com/44724892/202779212-9b14905d-d431-40ad-bea7-4cc14f90b185.png)

**Comment by Gambolico** [comment]
I have seen the example, but this is from having nonwalkable tile to puting a sprite and beeing walkable, what I want is in a walkable tile, putting an unwalkable gameObject to override the NavMesh, is that a posibility? Because my chest is always going to be in top of a walkable tile

**Comment by Gambolico** [comment]
You are totally right, indeed it is what I wanted, but for some reason I'm not able to replicate it.

Imma be trying for a while, ill come back with any feedback, thanks for the quick responses!

**Comment by Gambolico** [comment]
Testes all night and morning and cannot get it to work on my project, even though Im doing the same as the scene that you told me.

Is there anything im missing?

Default nonwalkable navmesh:

![image](https://user-images.githubusercontent.com/43265816/202846480-b354ed7c-b074-4087-9438-d9a01ef82edb.png)

Tilemap with walkable override

![image](https://user-images.githubusercontent.com/43265816/202846504-5b719652-e241-430c-8dda-35c315b33df5.png)

I removed the navMeshModifier from the walls tilemap to resemble the example you gave me.

Test square sprite with navModifier as override non walkable:

![image](https://user-images.githubusercontent.com/43265816/202846535-d0e27f66-6995-4282-b03d-307c2d45f34e.png)

When I bake the NavMeshSurface it doesnt do anything about the square sprite, even though in the example you gave me it does exactly what I want, but in mine it doesnt care about the nonwalkable sprite.

They are all in the same grid:

![image](https://user-images.githubusercontent.com/43265816/202846616-c17ed983-b8d0-44b5-807e-15ed140c31b9.png)

But when I bake this is the result:

![image](https://user-images.githubusercontent.com/43265816/202846629-a2c8eca0-abee-46d7-96e6-edb739baced7.png)

It does a good job with the tilemaps but doesnt do anything about the sprite with the NavMeshModifier. I must be doing something wrong for sure

**Comment by h8man** [comment]
Send me a test project, I will make a setup for you)

**Comment by Gambolico** [comment]
I was creating the test scene for you to look at, and when I create the same thing I have in my main project, it works on this new project. I don't know yet why it doesnt, but from a clear project I made it work. There must be something in my project that changes the behaviour.

Im gonna look into it and let you know

**Comment by Gambolico** [comment]
After a lot of work and removing the package and installing again, i've made it work!

![image](https://user-images.githubusercontent.com/43265816/202861990-a52d59cc-8320-4577-8f83-6ecfbcf84420.png)

I suppose in the testing I must have let something missconfigured, but now it's working.

Thank you so much for the quick responses man, without you pathmaking in 2D in Unity is a pain in the ass.

Lots of love!

**Comment by Gambolico** [comment]
I FOUND WHAT WAS HAPPENING!

I have the floor tilemap at z=3 and the wall tilemap at z=2.9, but I had my gameObjects at z=0 and then calculating the z depth.

At z=0 it didnt work, but when I have my gameObjects at z=2.8 it works perfectly.

Hope this can help someone else.

**Comment by Gambolico** [comment]
I have a question and I didnt want to open a new issue to ask it, in the bake at runtime section you say yo use a caching system to be able to rebake without losing the previous gameObjects. Is there an example of this?

Thanks in advance
