### ISSUE TITLE
Demo - NevMeshExtension requires a NavMeshSurface component

### ISSUE THREAD

**Issue by lurrow** [h8man/NavMeshPlus#103]
Hello,

I'm trying to implement the navMeshPlus following the .pdf, but i can't generate the bake.

I get the demo to copy the configurations, but if i clear and try to generate a new bake, nothing happens.

I recieve only "NevMeshExtension requires a NavMeshSurface component" error.

i'm using unity 2022.2.1f1 version

**Comment by h8man** [comment]
@lurrow 

I'm sorry, pdf is outdated. Use wiki instead https://github.com/h8man/NavMeshPlus/wiki

**Comment by lurrow** [comment]
Following the wiki, it's working, ty !

But, in unity 2022.2.1f1, nothing, exists a exception for this version?

**Comment by h8man** [comment]
Only started working on that

![image](https://user-images.githubusercontent.com/44724892/209485643-e88ebe54-fa8d-443f-8211-91f021ceeb19.png)

**Comment by h8man** [comment]
Just remove AI Navigation package and NavMeshPlus starts to work. Just a name collision. But why it installed by default on update? It's a good question
