### ISSUE TITLE
ArgumentNullException: Value cannot be null (Parameter name: key)

### ISSUE THREAD

**Issue by maxmistral** [h8man/NavMeshPlus#105]
When I try to bake the NavMeshSurface, I get the following error, is this a bug or an error on my part in using the library?

StackTrace : 
```
ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <d6232873609549b8a045fa15811a5bd3>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) (at <d6232873609549b8a045fa15811a5bd3>:0)
UnityEngine.AI.NavMeshBuilder2dState.GetMesh (UnityEngine.Sprite sprite) (at Library/PackageCache/com.h8man.2d.navmeshplus@42afaa2368/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:38)
```

**Comment by maxmistral** [comment]
Wrong Geometry used (Render mesh instead of physics collider)

**Comment by h8man** [comment]
This can only happen if sprite is null, maybe your sprite rendered have no sprites

**Comment by maxmistral** [comment]
> This can only happen if sprite is null, maybe your sprite rendered have no sprites

This is indeed what happened, I have renderer sprites attached to objects that I just use to specify a layer to my objects but they do not have sprites, on the other hand, these same objects have 2D colliders, that's what I was interested in, thank you for your quick response and your excellent library that seems to work perfectly!
