### ISSUE TITLE
Why my NavMesh data is not rendered properly on my tilemaps?

### ISSUE THREAD

**Issue by mekukun** [h8man/NavMeshPlus#106]
I have no idea why it's not rendering correctly. I've already made sure that I've set my tilemap layers to walkable and not walkable though. Is there anything else I should look at?

![image](https://user-images.githubusercontent.com/71602023/210175400-76604664-9056-45d6-93bf-f15441ae3ebe.png)

**Comment by h8man** [comment]
@mekukun Hello

This component "NavMeshSurface2d" is outdated, so I'm also not sure what is happening.
https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#nav-mesh-basics use this guide

**Comment by mekukun** [comment]
Still the same. The shape is too peculiar that I don't even know if my NavMeshModifier is the culprit.

![image](https://user-images.githubusercontent.com/71602023/210194237-720ae691-fbb9-44b9-8d9c-1d845e5a3614.png)

**Comment by h8man** [comment]
Try agent radius 0.01

**Comment by mekukun** [comment]
Nothing changed. and yeah, the cell size is 0.16.

**Comment by h8man** [comment]
Reduce size and bake again till you see changes
