### ISSUE TITLE
Agent gets stuck before reaching it's target

### ISSUE THREAD

**Issue by caneryasar** [h8man/NavMeshPlus#107]
I'm facing a weird problem, my agent goes wherever I click, except the ones on the same vertical alignment.  If I click and set a new destination on a grid/tile with same X value the agent gets stuck/incredibly slows down till it basically stops. Did anyone encounter a similar issue?

**Comment by h8man** [comment]
Yes, known issue https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#known-issues

The most common solution is to put rotation to 89.998 or something like this (don't forget to bake again)

**Comment by caneryasar** [comment]
Thanks for the fast reply! I'll inform again when I get the chance to try.

**Comment by caneryasar** [comment]
Thanks for the fast reply! I'll guess I overlooked it when I was reading How-To section.
