### ISSUE TITLE
Yellow error text stating the following - What to do with this?

### ISSUE THREAD

**Issue by ArravGames** [h8man/NavMeshPlus#108]
Assets\Standard Assets\Utility\EventSystemChecker.cs(18,13): warning CS0618: 'StandaloneInputModule.forceModuleActive' is obsolete: 'forceModuleActive has been deprecated. There is no need to force the module awake as StandaloneInputModule works for all platforms'
Printscreen photolink:

https://prnt.sc/_H0l6X4lqOTk

**Comment by h8man** [comment]
I don't think its related to component, it doesn't have any reference to  StandaloneInputModule
