### ISSUE TITLE
[FIXED] NavMesh not stretching to borders

### ISSUE THREAD

**Issue by jd-games95** [h8man/NavMeshPlus#109]
**FIXED:** Had to Open Agent Settings and reduce their radius. Sorry couldn't figure out how to delete this post

Hi,

i have an issue where the genetared NavMesh does not fully stretch towards the walls (see screenshot).
I was playing around with some settings and couldn't figure it out by myself.

Everything on default settings.

Architecture:

Grid (Grid)
- Ground (Tilemap, [NavMeshModifier, Override Area. Walkable])
- Walls (Tilemap, Tilemap Collider 2D, static Rigidbody2D, CompositeCollider2d, [NavMeshModifier, Override Area, Not Walkable])

NavMesh (NavMeshSurface2d)

![Unbenannt](https://user-images.githubusercontent.com/122102767/211027521-499f319a-7e16-4fd9-a769-02ad49f7e7f5.PNG)

The only thing i figured out so far is that activating the Composite Collider makes this area even smaller.
Nothing special done to tiles AFAIK. 

Would appreciate any type of help or hints. Ty!

**Comment by h8man** [comment]
Blue area shows where is CENTER of your agent can reach. So there always a gap

**Comment by jd-games95** [comment]
> Blue area shows where is CENTER of your agent can reach. So there always a gap

Okay that makes sense. My issue with this was that gaps that were only 1 tile wide were not passable. Which is also fixed by adjusting the agent radius then. Thanks for your reply!

**Comment by h8man** [comment]
Great! Thak you for feedback
