### ISSUE TITLE
Documentation - Use Geometry Physics Collides

### ISSUE THREAD

**Issue by brettsaunders21** [h8man/NavMeshPlus#11]
I am using the Unity Isometric Tilemap example and trying to convert that to use your navmesh system. In the demo, they use Decorations which use physics colliders. 

How do I go about doing this as I saw that you could do use geometry physics colliders, but can't get it to work? 
Am I also not sure how I could get physics colliders and tilemap working alongside each other as the demo uses for building the world?

**Comment by h8man** [comment]
NavMeshPlus currently cannot use physics. But it can use sprite mesh, and only for tiles
for second question - https://docs.unity3d.com/Manual/nav-MixingComponents.html
Use unity forum for questions and discusses. I'm also answering PMs.
