### ISSUE TITLE
NavMeshSurvace.UpdateNavMesh appears to be leaking Mesh objects

### ISSUE THREAD

**Issue by ksletmoe** [h8man/NavMeshPlus#110]
I'm using NavMeshPlus in a project where the mesh is build at runtime from a procedurally generated Tilemap. When the tilemap is updated in game, I call UpdateNavMesh on my NavMeshSurface object. I was profiling the game and noticed that the mesh count appears to climb by one every time UpdateNavMesh is called. When using the Memory Profiler plugin, I see that the only references to these mesh objects are self references (indicating they are indeed leaked).

The easiest way to reproduce I think would be to set up a project with a NavMeshSurface and CollectSources2d, and call UpdateNavMesh on the surface periodically in a Monobehaviour's update function. Open up the profiler and click on memory, and you can see the mesh count down at the bottom. You should see that tick up by one every time UpdateNavMesh is called.

![Screenshot 2023-01-10 203732](https://user-images.githubusercontent.com/5762006/211718778-0d203541-18c4-46c5-b697-01a91063a5ab.png)

**Comment by h8man** [comment]
@ksletmoe Got it. I will check and reply with updates.

**Comment by h8man** [comment]
Confirmed. Investigating.

**Comment by h8man** [comment]
It seems I have fixed it, but now CollectSourcesCache2d not working because of design issue.
By the way, if you used CollectSourcesCache2d there will be no leak.
