### ISSUE TITLE
In a multi-scene setup, only the Root objects of the last scene (highest index) are collected during the baking process.

### ISSUE THREAD

**Issue by Xenyrt** [h8man/NavMeshPlus#111]
For example if I have the following scenes loaded
- Scenery (contains a GameObject with a NavMeshSurface)
- GameDesign
- Light
only the Light scene is used to collect the GameObjects

It would be expected, at choice :
- the Root objects of the scene containing the NavMeshSurface are collected.
- the Root objects of all the loaded scenes are collected.

NavMeshBuilder2d.cs

```
public IEnumerable<GameObject> GetRoot()
        {
            switch (CollectObjects)
            {
                case CollectObjects.Children: return new[] { parent };
                case CollectObjects.Volume: 
                case CollectObjects.All:
                default:
                {
                    var list = new List<GameObject>();
                    for (int i = 0; i < SceneManager.sceneCount; ++i)
                    {
                        var s = SceneManager.GetSceneAt(i);
                        s.GetRootGameObjects(list); 
                    }
                    return list; <= list contains only root objects from last loaded scene.
                }
            }
        }
```

**Comment by h8man** [comment]
There is a component RootSources2d that adds extension. This extension overrides default behavior, and meant to be used in such scenarios.
Obviously you cannot reference any object outside your scene Scenery, so you need to add Light "roots" from a script on scene loading.

Or, there can be customRootSources2d extension that make collection in custom manner, like by scene name, tag, object search and etc.

Do you need any help with such implementation?

**Comment by Xenyrt** [comment]
Thank you for your quick answer.

RootSources2d meets my needs perfectly and if I ever need more you have put me on the track.

Thanks a lot :)
