### ISSUE TITLE
NavMeshSurface - The type or namespace name 'MonoBehaviour'

### ISSUE THREAD

**Issue by ksamnole** [h8man/NavMeshPlus#113]
Hello. The following problem has arisen - when starting the game in the editor, everything works correctly. But if I build a project, 68 errors appear.

![image](https://user-images.githubusercontent.com/35575959/212565508-168ad61c-abf0-4af0-a9e7-2dea6ff6a7c2.png)

**Comment by ksamnole** [comment]
I tried to install through the package manager, but still the same error.

**Comment by h8man** [comment]
@ksamnole 

Got it. Its not in my regular test cases, so It would be. I will check

**Comment by ksamnole** [comment]
Thanks for the quick response :)

**Comment by fiery123** [comment]
same thing on 2021.3.15f1

**Comment by h8man** [comment]
@IJsLauw You are right, I just used MSVS to add references, but it made bad decisions on where to put it.

**Comment by ksamnole** [comment]
@h8man Thanks! Everything is working fine now.
