### ISSUE TITLE
Problem with Calculating and drawing path

### ISSUE THREAD

**Issue by BordexDev** [h8man/NavMeshPlus#114]
I am trying to calculate and then draw a path between 2 positions, this should work but it doesnt ```
NavMesh.CalculatePath(transform.position, hosePos.position, NavMesh.AllAreas, path);
        lineRenderer.positionCount = path.corners.Length;
        lineRenderer.SetPosition(0, transform.position);
            for (int i = 1; i < path.corners.Length; i++)
            {
                Vector3 pointPosition = new Vector3(path.corners[i].x, path.corners[i].y, path.corners[i].z);
                lineRenderer.SetPosition(i, pointPosition);
            } 
``` The NavMesh.CalculatePath returns false. How can I solve this ?

**Comment by h8man** [comment]
https://github.com/h8man/RedHotSweetPepper/blob/master/Assets/Scripts/Navigate.cs

Here is working sample used in a demo I created

**Comment by BordexDev** [comment]
The demo is working, thanks ! Can I ask you how can I visulize it in a line renderer and not Gizmos ?

**Comment by h8man** [comment]
I suppose just copy code and replace with line renderer API.
I never used Line Renderer, so it out of my scope.
