### ISSUE TITLE
Player gets stuck moving on Y axis.

### ISSUE THREAD

**Issue by BordexDev** [h8man/NavMeshPlus#117]
When I am using top-down like movement when player is moving up(on Y axis) he gets sometimes stuck. The NavMesh has to be causing it since when I disable the NavMesh it works just fine. Could it be because of ```agent.updateUpAxis = false;``` ? Also here is a video of it. 

https://user-images.githubusercontent.com/122821813/213264012-71482608-9f38-4657-982c-ab6b685019d5.mp4

**Comment by h8man** [comment]
@BordexDev 

Known issue, but it has workaround https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#known-issues

 _By default navmesh now have a small tilt 89.98 to make agent work_

check is your navmesh object have small tilt

**Comment by BordexDev** [comment]
I found a better fix for it. Put your NavMeshAgent component onto child object of the player. 
1. If you need to just calculate path, on the child object do ```transform.position = player.transform.position``` 
2. If you need to just move the player on the path, on the player object do ```transform.position = child.transform.position```

Feel free to use this in the HOW TO section if you want to.

**Comment by h8man** [comment]
@BordexDev I'm working on AgentOverride components, I will consider this as an option
