### ISSUE TITLE
Source as unity package

### ISSUE THREAD

**Issue by KorDum** [h8man/NavMeshPlus#12]
Hi!
Can you add package.json for use sources as Unity Package? Like these https://github.com/Unity-Technologies/2d-extras

**Comment by h8man** [comment]
Hi,
Please verify this, it works for me: 
    "com.h8man.2d.navmeshplus": "https://github.com/h8man/NavMeshPlus.git#package",

**Comment by KorDum** [comment]
Thanks! It's works perfectly! You can merge these into master or somewhere :)

**Comment by h8man** [comment]
Now it should be "com.h8man.2d.navmeshplus": "https://github.com/h8man/NavMeshPlus.git#master"

**Comment by KorDum** [comment]
Thanks a lot!  
Can you add this to Readme.md? For other coders :)

**Comment by h8man** [comment]
Sure
