### ISSUE TITLE
Where is the script of the agent?

### ISSUE THREAD

**Issue by Kiogra** [h8man/NavMeshPlus#121]
I didn't seen it in the code

**Comment by h8man** [comment]
Agent is Unity component, there is no source code for it. Even in Unity's repo, as it is a native C++ component

**Comment by Kiogra** [comment]
Oh. sorry
In add component i can't find it, some help?

**Comment by Kiogra** [comment]
And there is for 2d right?

**Comment by h8man** [comment]
There is no 2d Agent, only component to disable axis rotation [AgentOverride2d.cs]
Most cases covered in https://github.com/h8man/RedHotSweetPepper

**Comment by Kiogra** [comment]
Oh, https://futbolstudiohistorietas.com/navmesh-2d-unity/ i used this guide. So sad.

Did you know how to make an npc follow a chosen path
