### ISSUE TITLE
Half of Tilemap baked perfectly

### ISSUE THREAD

**Issue by CMorooney** [h8man/NavMeshPlus#122]
I have 3 tile maps with `NavMeshModifier`s

the tilemaps under the `Walkable` are..well, walkable. And the others are not. You can see at the top half of the map the intention of the layers as the tool works beautifully.

![Screenshot 2023-02-10 at 6 52 51 PM](https://user-images.githubusercontent.com/1463446/218223564-6b297602-7313-4603-8050-8c8af98a5777.png)

but I cannot for the life of me figure out why it's not _all_ correct. I do notice some edges are white (instead of black) in the navmesh gizmo over the problem area, though that's not the only instance of that. Has anyone seen this? My Nav Mesh Surface GameObject just has `NavMesh CollectSources2d` and `NavMeshSurface` components with default settings, rotated.

**Comment by h8man** [comment]
Make sure that you don't have Unity Navigation.AI package, as we have name collisions
Disable tilemaps one by one for trouble shooting.

**Comment by CMorooney** [comment]
I eventually figured out that my object with the NavMeshSurface component had an _ever_ so slightly different X rotation than the tilemaps somehow -- setting each to be rotated 90deg manually solved my issue.

looking back at the problem with that in mind, it makes sense. So I'm closing this -- thanks for your response and your library!

**Comment by h8man** [comment]
Hmmmm. Its intentionally 89.98, as this rotation fixes Agent navigation on straight pass on Y.
Can you share more details? maybe I should switch back to 90

**Comment by CMorooney** [comment]
maybe I set something up wrong with my tilemaps in relation to that object and it's 89.98 XRot offset...

but I have tried the following and none have gotten the desired result in the same way that switching that offset to a 90 has:

- making the tilemaps children of the NavMeshSurface/Collect Sources game object
    - This auto-sets the tilemap's XRotation to 90, I get the "half-bake"
    - Tried adjusting the tilemap offset angle to match the parent object, same "half-bake" result

- making the tilemaps a sibling of the NavMeshSurface/CollectSources game object
    - Tilemaps XRotation is defaulted to 0, I get "half-bake"
    - Tried adjust the tilemap offset to be complimentary to the NavMesh object (setting it to +-89.98 basically make it invisible so I was trying +-.02) and still got the "half-bake" result
    
I will have to look into the workaround that is odd offset exists for and see if it's occurring for me at 90deg.

I should note just in case that the tilemaps are generated from [LDtk](https://ldtk.io) via (LDtkToUnity)[https://github.com/Cammin/LDtkToUnity]

**Comment by CMorooney** [comment]
this is a short/shitty gif of my agents running around (bottom left corner) -- this is with the hard 90deg XRotation (and the 
 correct nav mesh I would expect with my tileset)

From what I understand that slight .02 offset was to solve stuck agents moving in the Y direction? I see a few of these guys going directly up crosswalks no problem, but it's possible I misunderstood that problem

![desktop-front-idle](https://user-images.githubusercontent.com/1463446/218320254-3b9503c9-0056-49fa-8410-487baceb7a48.gif)

**Comment by h8man** [comment]
Can you send minimal test project for troubleshooting?

**Comment by CMorooney** [comment]
> Can you send minimal test project for troubleshooting?
sorry for the late response...I've somewhat moved on for now onto other projects. Unfortunately I don't have a minimal repo but this is the project I was working on when coming across this problem

https://github.com/CMorooney/CannibalRunUnity
