### ISSUE TITLE
Baking mesh at runtime

### ISSUE THREAD

**Issue by noelDamadian** [h8man/NavMeshPlus#123]
Hello.
im having trouble baking the mesh in code. i created a script to controll certain aspects of the nav mesh, but i cannot reference the NavMeshSurface component.
![image](https://user-images.githubusercontent.com/87284296/218713554-fbfb2beb-a305-420d-8420-fa31d26dbf1f.png)

im new to Git and not very good at programming so im kinda lost.

**Comment by h8man** [comment]
namespace NavMeshPlus.Components

**Comment by noelDamadian** [comment]
thanks :D
