### ISSUE TITLE
cant seem to get it to work in unity 2022.2.2f1

### ISSUE THREAD

**Issue by vacantknight** [h8man/NavMeshPlus#124]
i followed the wiki and i worked for me before in unity 2021 but when i switched to unity 2022 it stopped working and i cant seem to get it to work anymore no matter what i do, it wont even seem to bake
![bgxdfbxfbxfb](https://user-images.githubusercontent.com/125716274/219829770-4e5d1714-c0aa-4b9d-827f-146e145ec905.PNG)
![Capture](https://user-images.githubusercontent.com/125716274/219829771-9484068d-3deb-435b-8290-b6583a5b0e1f.PNG)
![ghsdgsdrg](https://user-images.githubusercontent.com/125716274/219829773-f1527a01-dc61-4948-81c8-4ae973ad049a.PNG)

**Comment by h8man** [comment]
Remove Navigation.AI. We have names collision.

New names starts with "Navigation"

Create Empty Object in scene root.
Add "Navigation Surface" component to Empty Object and add NavMeshCollecSources2d component after.
Click Rotate Surface to XY (to face surface toward standard 2d camera x-90;y0;z0)
Add "Navigation Modifier" component to scene objects obstacles, override the area.
In "Navigation Surface" hit Bake.

**Comment by vacantknight** [comment]
![ffsdfsd](https://user-images.githubusercontent.com/125716274/219876950-f91caee4-f46f-46ba-abe4-92d183240c98.PNG)
i remove this?

**Comment by vacantknight** [comment]
ok thanks i see it works now

**Comment by vacantknight** [comment]
> Remove Navigation.AI. We have names collision.
> 
> New names starts with "Navigation"
> 
> Create Empty Object in scene root. Add "Navigation Surface" component to Empty Object and add NavMeshCollecSources2d component after. Click Rotate Surface to XY (to face surface toward standard 2d camera x-90;y0;z0) Add "Navigation Modifier" component to scene objects obstacles, override the area. In "Navigation Surface" hit Bake.

ok thanks i see it works now, it bakes but i dont see nav mesh agent components anymore after removing that so i cant get movement now

**Comment by h8man** [comment]
NavMeshAgent https://docs.unity3d.com/ScriptReference/AI.NavMeshAgent.html is not a part of any package, its Unitity's built in component.

**Comment by vacantknight** [comment]
so the Ai navigation package if removed can bake but also if removed it removes nav mesh agent from component list so i dont know whats going on, nav mesh agent seems to be tied to the Ai.Navagation package as it goes away when uninstalling the package

**Comment by h8man** [comment]
https://github.com/h8man/NavMeshPlus/issues/125

you can install Navigation.AI back
