### ISSUE TITLE
Can't change baking offset size

### ISSUE THREAD

**Issue by drizztdourden08** [h8man/NavMeshPlus#125]
Hey,

Either the documentation is lacking, I don't understand it or there is something that's missing.

I was previously using the old navmeshsurface2d and the mix between navigation.AI and this seems to be working great at the times. With this one, I feel like there are missing features that are essential to the process.

My issue:
I have a navMesh with both a surface and collect components.
I have a "Layout" GO that contain every elements with modifier (That wasn't necessary before)
The game generate a map procedurally and use tilemap to render it with composite colliders.
The player will construct "Building" that takes up 1 cell of space on the grid. The mesh is updated each times (as shown in the documentation).

Enemies will follow a straight line form their starting point to the end point, unless there are these building in the way, which they should avoid. They should be able to navigate in a 1 cell space between building.

I can't seems to find what to modify no matter what I try in order to modify how the mesh is baked and the offset between the collider (I use physics collider here), and the actual mesh.

--------

The real issue:
    - It is very hard to troubleshoot without the mesh gizmo. I don't have it, at least in 2022.2 1f1. My only workaround is selecting the navmesh agents and I can see the calculated possible area with them, but not the actual full mesh. (like in the screenshot) It is not in the Gizmo list.
    - I can't open the "Agent Type" option and I am stuck with "humanoid" default configuration. I have tried reinstalling Navigation.AI just to modify the agent but it breaks so much stuff and is hard to get back to a working point.

I am pretty sure I was modifying the agent in the past to change that but can't right now.

Just to be clear, the navmesh baking seems to be working, but I can see with the agent that it's path doesn't go further than about half a cell from the collider. Meaning, between two "building", there is one cell of space and thus add up to 1 full cell where they can't walk. If there is two cells of space between the building, then it gives 1 cell for the agent to go through. I want the baking to have 0 offset with the collider. 1 cell of space free between the buildings.

I have tried pretty much every option I could think of, from all of your scripts and components to every options on the navmesh Agent and colliders themselves.

Any help would be appreciated.

**Comment by h8man** [comment]
please provide and image with an issue you have

**Comment by drizztdourden08** [comment]
Here's the screenshot while it plays out. the "Darker" part is the calculated path of all the enemies selected. I'm not sure if this features was there before in Unity. This is my only was of seeing the baked mesh right now. Not sure if it's an issue with your plugin or the new unity version.

anyhow, here what it looks like:
![image](https://user-images.githubusercontent.com/36481532/220409848-5f99c760-0a2e-4f5d-8e0f-e0b002bf4b7d.png)

In this case, they can get through the first column of towers because there two cells of opening to get through. They'll get stuck as far as they can on the second one cause only 1 cell paths are available. I'd like the path calculated to be perfectly aligner with the colliders (They align with the grid floor we can see, which is always 1 cell.

**Comment by drizztdourden08** [comment]
By “agent”, you mean the “Agent Type” that can be set on the nav mesh surface?

this can’t be accessed. It says navigate.AI is required to modify this. And we both know this is not compatible and can’t be installed.

do you know any way to modify the agent type settings other than with the navigate.ai module?

**Comment by h8man** [comment]
I just checked Unity 2022.1, you right, navigation panel moved to package!

You can install  navigate.AI, just pay attention to component names  "Navigation" vs "NavMesh"

I made some terrible decision yet again, I'll try to have some time and fix it

**Comment by drizztdourden08** [comment]
Is there any place to modify the agent without the UI? Last time I installed the navigation package, it broke pretty much the whole thing and had to remove and re-configure all components or else, errors wouldn’t go away.

if there is any way to create an agent through code or just a file edit outside of unity, I’d do that. Can’t find the doc that relate to agent type. And your navmesh is set using the “id” of this agent type.

If you know of any way, let me know. That’d be a great workaround in the meantime.

**Comment by h8man** [comment]
Everything should work fine. Back up your project and check it

![image](https://user-images.githubusercontent.com/44724892/220469505-694874cd-879d-4003-a3bf-e64ce1df8e52.png)

**Comment by drizztdourden08** [comment]
I tried that 3 times and somehow, this times, it works.

I'm not even sure I want to know why. :P but I'm grateful for your help. I have all the tools I require now to make this works. And adjusting the agent size is exactly what I needed.

Thanks.
