### ISSUE TITLE
Runtime Render-Mesh-Baking buggy

### ISSUE THREAD

**Issue by Zai-shen** [h8man/NavMeshPlus#126]
Hello,
for the love of all that is holy, I can't figure out while my NavMesh doesn't get baked properly.

Setup:
Unity 2021.3.18f1 (2D URP)
DungeonArchitect 1.20.0
NavMeshPlus 0.2.15

I'm creating a runtime dungeon, and after it is fully generated, I try to bake the navmesh for it. I've followed both the How-To and the Runtime-Demo scene. If I pre-build the dungeon in editor, and let the navmesh bake there (Render Meshes), I'll get a correct display:

![FullBakedMeshEditor](https://user-images.githubusercontent.com/32803592/220348804-c5c86e30-d9a5-4416-8266-8e8b2ceaa9b7.PNG)

If I do it at runtime, only half or even less of the surfaces get baked:

![HalfBakedMeshRuntime](https://user-images.githubusercontent.com/32803592/220349118-e4d570f7-8149-403e-bfd5-40e164df72e8.PNG)

If I enable to bake it as (Physics Colliders) runtime, I get a correct (though not the desired) result.
![FullBakedCollidersRuntime](https://user-images.githubusercontent.com/32803592/220349283-393fc567-94cb-4f08-bad0-9b78e4fab366.PNG)

Is there any way I could've gone wrong anywhere? I've checked for script execution multiple times, should be fine.
Any help is appreciated.

**Comment by h8man** [comment]
no updates
