### ISSUE TITLE
NavMesh not correctly generated around obstacles for larger Tilemaps

### ISSUE THREAD

**Issue by VolkanKutlar** [h8man/NavMeshPlus#132]
Hey,

I am trying to write a 2D game in which I am generating a single island at runtime using Tiles and Tilemaps. The generation itself is working fine, even when setting the size of the map to a few kilometers and having tens of millions of tiles generated.

However, I also would like AI to inhabit that island. For pathfinding, I am using NavMeshPlus for the 2D Navmesh generation. However, it seems like only a fraction of the whole map is actually receiving a correctly generated NavMesh around Obstacles:

![grafik](https://user-images.githubusercontent.com/17934834/228343936-462a2a20-81f8-47af-bdd8-f83878ffae94.png)

The black lines at the top,  indicate the correctly drawn Navmesh around obstacles. As you can see, after a small fraction at the top of the map, obstacles are simply ignored. Everything below that section will simply be markes as walkable. It seems like after a certain value for the y coordinate, the generator simply stops checking for obstacles and just marks everything as such:

![grafik](https://user-images.githubusercontent.com/17934834/228344455-0ba4c65f-a122-474a-a38e-8be7cbda4942.png)

In this example, I reduced the size of the map to 1/4 of its original value. You can clearly see that a large part of obstacles are taken into consideration as opposed to the example above. However, even some obstacles at the bottom side are still being ignored:

![grafik](https://user-images.githubusercontent.com/17934834/228344854-9b1b6c08-54f4-4e7f-894c-02c084e5e158.png)

I marked correctly considered obstacles in blue and ignored obstacles in red.

This is weird because up to a certain size of the NavMesh, the generation is working fine and obstacles are avoided.

All tilemaps have been marked as static and use the Navigation Modifier component as walkable or not walkable.

Does anyone know how I can solve this? is there some kind of hardcoded value which prevents obstacles from being considered after a certain threshold has been reached?

**Comment by h8man** [comment]
I'm have nothing against A* Pathfinding. Great tool.
