### ISSUE TITLE
NavMeshExtension requires a NavMeshSurface component

### ISSUE THREAD

**Issue by Ben-Ankers** [h8man/NavMeshPlus#135]
Hi,

I have been trying to add a navmesh onto my tilemap but everytime I try and add NavMesh CollectSourced2D to the object which has the NavMeshSurface component on it I get this error.

"NavMeshExtension requres a NavMeshSurface component"

Is there something I am missing or is there an issue?

**Comment by h8man** [comment]
To use it in your project:

Copy repo into your Asset folder (or install as a package).
Create Empty Object in scene root.
Add "Navigation Surface" component to Empty Object and add NavMeshCollecSources2d component after.
Click Rotate Surface to XY (to face surface toward standard 2d camera x-90;y0;z0)
Add "Navigation Modifier" component to scene objects obstacles, override the area.
In "Navigation Surface" hit Bake.

pay attention to naming. Component should have name  "Navigation Surface"

**Comment by Ben-Ankers** [comment]
Thanks for this.

I was following the instructions in the "How To" section of the github which seems to be outdated.

**Comment by h8man** [comment]
Seems you are right. I'll update it
