### ISSUE TITLE
Destroy may not be called from edit mode! Use DestroyImmediate instead.

### ISSUE THREAD

**Issue by IamBogdan** [h8man/NavMeshPlus#136]
Hello!

I have an issue (On Unity 2021.3.11f1). I created an empty object, added Navigation Surface and CollecSources2d to it. Then I clicked "Rotate Surface to XY" and selected "Physics Colliders" in "Use Geometry".
Next, I created two tilemaps and added Navigation Modifiers to them, selecting "Not Walkable". Then I clicked "Bake" and got the following error:

```
Destroy may not be called from edit mode! Use DestroyImmediate instead.
Destroying an object in edit mode destroys it permanently.
UnityEngine.Object:Destroy (UnityEngine.Object)
NavMeshPlus.Extensions.NavMeshBuilder2dState:Dispose (bool) (at Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:119)
NavMeshPlus.Extensions.NavMeshBuilder2dState:Dispose () (at Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:132)
NavMeshPlus.Extensions.CompositeDisposable:Dispose (bool) (at Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshBuilderState.cs:90)
NavMeshPlus.Extensions.CompositeDisposable:Dispose () (at Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshBuilderState.cs:104)
NavMeshPlus.Extensions.NavMeshBuilderState:Dispose (bool) (at Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshBuilderState.cs:45)
NavMeshPlus.Extensions.NavMeshBuilderState:Dispose () (at Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshBuilderState.cs:57)
NavMeshPlus.Components.NavMeshSurface:UpdateNavMesh (UnityEngine.AI.NavMeshData) (at Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshSurface.cs:235)
NavMeshPlus.Editors.Components.NavMeshAssetManager:StartBakingSurfaces (UnityEngine.Object[]) (at Assets/NavMeshPlus/NavMeshComponents/Editor/NavMeshAssetManager.cs:127)
NavMeshPlus.Editors.Components.NavMeshSurfaceEditor:OnInspectorGUI () (at Assets/NavMeshPlus/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs:264)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

The error occurs when "Physics Colliders" is selected, but if "Render Meshes" is selected, the error does not appear.

Did I do something wrong or is this an error in the library?

**Comment by h8man** [comment]
Its error in library. Thak you for a feedback. I'll fix it in few days

**Comment by langyinan** [comment]
When I add the Navigation Surface first and then add NavMesh CollectSource2d, the error will occur:


![](https://cdn.discordapp.com/attachments/1091706535140397076/1095490725300424724/image.png)

`Destroy may not be called from edit mode! Use DestroyImmediate instead.
Destroying an object in edit mode destroys it permanently.
UnityEngine.Object:Destroy (UnityEngine.Object)
NavMeshPlus.Extensions.NavMeshBuilder2dState:Dispose (bool) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:115)
NavMeshPlus.Extensions.NavMeshBuilder2dState:Dispose () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:132)
NavMeshPlus.Extensions.CompositeDisposable:Dispose (bool) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilderState.cs:90)
NavMeshPlus.Extensions.CompositeDisposable:Dispose () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilderState.cs:104)
NavMeshPlus.Extensions.NavMeshBuilderState:Dispose (bool) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilderState.cs:45)
NavMeshPlus.Extensions.NavMeshBuilderState:Dispose () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilderState.cs:57)
NavMeshPlus.Components.NavMeshSurface:UpdateNavMesh (UnityEngine.AI.NavMeshData) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshSurface.cs:235)
NavMeshPlus.Editors.Components.NavMeshAssetManager:StartBakingSurfaces (UnityEngine.Object[]) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Editor/NavMeshAssetManager.cs:127)
NavMeshPlus.Editors.Components.NavMeshSurfaceEditor:OnInspectorGUI () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs:264)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`

And: 

`ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <27586baf39bf4babbfd8a2caabe8e228>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) (at <27586baf39bf4babbfd8a2caabe8e228>:0)
NavMeshPlus.Extensions.NavMeshBuilder2dState.GetMesh (UnityEngine.Sprite sprite) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:44)
NavMeshPlus.Extensions.NavMeshBuilder2d.CollectSources (System.Collections.Generic.List`1[T] sources, UnityEngine.SpriteRenderer spriteRenderer, System.Int32 area, NavMeshPlus.Extensions.NavMeshBuilder2dState builder) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:228)
NavMeshPlus.Extensions.NavMeshBuilder2d.CollectSources (System.Collections.Generic.List`1[T] sources, NavMeshPlus.Extensions.NavMeshBuilder2dState builder, NavMeshPlus.Components.NavMeshModifier modifier, System.Int32 area) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:199)
NavMeshPlus.Extensions.NavMeshBuilder2d.CollectSources (UnityEngine.GameObject root, System.Collections.Generic.List`1[T] sources, NavMeshPlus.Extensions.NavMeshBuilder2dState builder) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:174)
NavMeshPlus.Extensions.NavMeshBuilder2d.CollectSources (System.Collections.Generic.List`1[T] sources, NavMeshPlus.Extensions.NavMeshBuilder2dState builder) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:144)
NavMeshPlus.Extensions.CollectSources2d.CollectSources (NavMeshPlus.Components.NavMeshSurface surface, System.Collections.Generic.List`1[T] sources, NavMeshPlus.Extensions.NavMeshBuilderState navNeshState) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/CollectSources2d.cs:87)
NavMeshPlus.Components.NavMeshSurface.CollectSources (NavMeshPlus.Extensions.NavMeshBuilderState builderState) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshSurface.cs:366)
NavMeshPlus.Components.NavMeshSurface.UpdateNavMesh (UnityEngine.AI.NavMeshData data) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshSurface.cs:221)
NavMeshPlus.Editors.Components.NavMeshAssetManager.StartBakingSurfaces (UnityEngine.Object[] surfaces) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Editor/NavMeshAssetManager.cs:127)
NavMeshPlus.Editors.Components.NavMeshSurfaceEditor.OnInspectorGUI () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs:264)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass71_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <fb48b454ac8e48ea94ca980d999e307f>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)`

But when I delete the Navigation Surface and then add it back (NavMesh CollectSources2d stays), the bake would work but no mesh seems to be created. I am using 2022.2.13.

**Comment by 3dthief** [comment]
I have a problem with Render Meshes too. Unity version 2022.2.5f1 (NavMeshPlus 0.2.16 installed from https://github.com/h8man/NavMeshPlus.git) - Unity registry AI Navigation 1.1.1 removed.

> Destroy may not be called from edit mode! Use DestroyImmediate instead.
> Destroying an object in edit mode destroys it permanently.
> UnityEngine.Object:Destroy (UnityEngine.Object)
> NavMeshPlus.Extensions.NavMeshBuilder2dState:Dispose (bool) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:115)
> NavMeshPlus.Extensions.NavMeshBuilder2dState:Dispose () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilder2d.cs:132)
> NavMeshPlus.Extensions.CompositeDisposable:Dispose (bool) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilderState.cs:90)
> NavMeshPlus.Extensions.CompositeDisposable:Dispose () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilderState.cs:104)
> NavMeshPlus.Extensions.NavMeshBuilderState:Dispose (bool) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilderState.cs:45)
> NavMeshPlus.Extensions.NavMeshBuilderState:Dispose () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshBuilderState.cs:57)
> NavMeshPlus.Components.NavMeshSurface:UpdateNavMesh (UnityEngine.AI.NavMeshData) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Scripts/NavMeshSurface.cs:235)
> NavMeshPlus.Editors.Components.NavMeshAssetManager:StartBakingSurfaces (UnityEngine.Object[]) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Editor/NavMeshAssetManager.cs:127)
> NavMeshPlus.Editors.Components.NavMeshSurfaceEditor:OnInspectorGUI () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@c7ea1f1771/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs:264)
> UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by h8man** [comment]
Hope it fixed
