### ISSUE TITLE
Agents avoiding NavigationLink

### ISSUE THREAD

**Issue by ghost** [h8man/NavMeshPlus#137]
My agents seem to want to avoid navigation links even with their cost is set to -1. They will use the links if it's the only available path to them, but otherwise will travel incredibly out of their way to avoid using them. I'm using the default Walkable and Not Walkable states for all navigation modifiers.

**Comment by h8man** [comment]
@bryantmakesprog I will add this test scenario to check.

**Comment by h8man** [comment]
add sample scene commit/c861a301819e801cd8a8bf43cfe39af0d2092dde
