### ISSUE TITLE
NavMeshSurface2d not showing up

### ISSUE THREAD

**Issue by moshiggg** [h8man/NavMeshPlus#138]
Hello it seems that whenever i try to add "NavMeshSurface2d" onto an Empty GameObject it simply wont show up in the components. I've tried redownloading it but its not showing up? 

I don't know if this is a me issue or...?

Thanks! :)

**Comment by TheFabiocool** [comment]
Same happening to me.
Using LTS 2021.3.23f1

**Comment by Alen7771** [comment]
The same problem

**Comment by Alen7771** [comment]
> Hello it seems that whenever i try to add "NavMeshSurface2d" onto an Empty GameObject it simply wont show up in the components. I've tried redownloading it but its not showing up?
> 
> I don't know if this is a me issue or...?
> 
> Thanks! :)


Use this version 
https://github.com/h8man/NavMeshPlus/tree/c8c7629c23803e94cc0729bcc39de1885dc04fdf

**Comment by Alen7771** [comment]
> Same happening to me. Using LTS 2021.3.23f1

Use this version
https://github.com/h8man/NavMeshPlus/tree/c8c7629c23803e94cc0729bcc39de1885dc04fdf

**Comment by h8man** [comment]
There is no "NavMeshSurface2d", It was removed few month ago.

Copy repo into your Asset folder (or install as a package).
Create Empty Object in scene root.
Add **"Navigation Surface"** component to Empty Object and add **NavMeshCollecSources2d** component after.
Click Rotate Surface to XY (to face surface toward standard 2d camera x-90;y0;z0)
Add **"Navigation Modifier"** component to scene objects obstacles, override the area.
In **"Navigation Surface"** hit Bake.

**Comment by GustavoContreiras** [comment]
Omg please someone update the instructions. This step is so important.

**Comment by h8man** [comment]
@GustavoContreiras readme updated. Wiki - not so much. Please create a PR
