### ISSUE TITLE
Dynamic obstacles

### ISSUE THREAD

**Issue by imigalkin** [h8man/NavMeshPlus#14]
Hi, sorry if this question is silly (i am newbie in unity)

Is this mesh support dynamic obstacles?

**Comment by h8man** [comment]
Hi,
It's not 'this' mesh, it's unity's NavMesh. Yes its supports moving obstacles.
So you can use unity docs and forums https://docs.unity3d.com/Manual/class-NavMeshObstacle.html

**Comment by imigalkin** [comment]
Tnx for response! =)
