### ISSUE TITLE
Can't bake surface with NavMesh CollectSources2D

### ISSUE THREAD

**Issue by MarcosChedid** [h8man/NavMeshPlus#142]
When i try to bake the surface, after i've done all the process of adding **NavSurface** and **NavMesh CollectSources2D** to the **NavMesh object** and **NavModifier** to each **tilemap** i'm using, this error shows up and **don't allows me to bake.**

![NavMeshError1](https://user-images.githubusercontent.com/74746015/235042977-07757b82-58a4-41a6-8613-5bd4664f65c6.jpg)
![NavMeshError2](https://user-images.githubusercontent.com/74746015/235042982-0c9c6297-a9f3-4c60-872e-f9cd96b6e58a.jpg)

If i bake without **"NavMesh CollectSources2D"** it goes normally, it only happens when the script is on.

**Comment by h8man** [comment]
Seems some sprites doesn't have mesh. Ill fix it soon

**Comment by h8man** [comment]
Done
