### ISSUE TITLE
I cant see NavMeshCollecSources2d in components.

### ISSUE THREAD

**Issue by Ask-er** [h8man/NavMeshPlus#144]
I downloaded from package manager. NavMeshCollecSources2d is missing.

**Comment by h8man** [comment]
We got some renaming that is not final. I don't have enough time to update documentation as we will have updates soon.

New name:
    [AddComponentMenu("Navigation/NavMesh CollectSources2d", 30)]
    public class CollectSources2d: NavMeshExtension
