### ISSUE TITLE
Unity 2022.3.0 (LTS) error: NavMeshExtension requires NavMeshSurface component

### ISSUE THREAD

**Issue by 3rd-Culture** [h8man/NavMeshPlus#147]
hey there h8man,
I've recently upgraded one of my projects that uses the NavMeshPlus extension to Unity 2022.3.0f1 (LTS) and encountered a pretty annoying bug.
i was previously using Unity 2021.3.18f1 (LTS) and there were no issues.
When I run the game in the updated version of Unity I get 2 LogWarnings:

1) 
NavMeshExtension requires a NavMeshSurface component
UnityEngine.Debug:LogError (object)
NavMeshComponents.Extensions.NavMeshExtension:ConnectToVcam (bool) (at Assets/TAG_TOWER/NavMeshPlus-master/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshExtension.cs:47)
NavMeshComponents.Extensions.NavMeshExtension:OnScriptReload () (at Assets/TAG_TOWER/NavMeshPlus-master/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshExtension.cs:36)

and 2)
NavMeshExtension requires a NavMeshSurface component
UnityEngine.Debug:LogError (object)
NavMeshComponents.Extensions.NavMeshExtension:ConnectToVcam (bool) (at Assets/TAG_TOWER/NavMeshPlus-master/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshExtension.cs:47)
NavMeshComponents.Extensions.NavMeshExtension:Awake () (at Assets/TAG_TOWER/NavMeshPlus-master/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshExtension.cs:27)

I have already tried deleting and re-importing the package, and building up the navmesh agents, navmesh surface and navmesh modifiers from scratch...but to no avail.
Any help towards finding a solution would be greatly appreciated as my enemy movement is heavily dependent on this asset.

thanks in advance,
Jesse

**Comment by h8man** [comment]
I didn't update documentation as I'm not satisfied with current implementation, and it is subjected to frequent changes)

But pay attention to  "Navigation Surface"(mine)  and "NavMesh Surface"(AI.Navigation)

Copy repo into your Asset folder (or install as a package).
Create Empty Object in scene root.
Add "Navigation Surface" component to Empty Object and add NavMeshCollecSources2d component after.
Click Rotate Surface to XY (to face surface toward standard 2d camera x-90;y0;z0)
Add "Navigation Modifier" component to scene objects obstacles, override the area.
In "Navigation Surface" hit Bake.

**Comment by 3rd-Culture** [comment]
hey h8man,
just a quick update...i redownloaded the package and imported it to my project and was able to see the Navigation Surface component.
Thanks again for your help! :D
