### ISSUE TITLE
Randomly sprite rotation

### ISSUE THREAD

**Issue by kirill93536** [h8man/NavMeshPlus#148]
Recently when I start my game the gameobject with NavMeshAgent starts rtotating weirdly. As I think it should be rotating only by z axis, but it rotates x and y also. Is it bug or I did something wrong? Because if I disable NavMeshAgent it returns to normal state and also if I remove baked navmesh rotation becomes normal.

**Comment by h8man** [comment]
Add [AgentOverride2d.cs] component.

Please check  demo project for rotation options https://github.com/h8man/RedHotSweetPepper

**Comment by kirill93536** [comment]
Oh, thank you, that helped. I thought that was bug, because project wroked without that for 2 or 3 days)
