### ISSUE TITLE
Agent just disappears

### ISSUE THREAD

**Issue by Willyema** [h8man/NavMeshPlus#149]
In scene view I see it fine, when I start the gaqme the agent disappears, though it can still move but just goes to the ground instantly, I am making a topdown view 3d game

**Comment by h8man** [comment]
if you making 3d game this package is not suited well. Regular AI.Navigation should work.

Also check this issue https://github.com/h8man/NavMeshPlus/issues/148

**Comment by Willyema** [comment]
Sorry, I made a typo, it was meant to be a 2D top down game, also i fixedthe going down but it still disappears, like in the editor i seenit but in the game it has no texture

**Comment by Willyema** [comment]
Also is there a way to disable physics for the agent?

**Comment by h8man** [comment]
Yes, you can enable rotation AgentRotate2d.cs or AgentRotateSmooth2d.cs

Agent doesn't obey physics, it is part of NavMesh system. https://docs.unity3d.com/Manual/nav-MixingComponents.html
