### ISSUE TITLE
Bake Button doesn't do anything

### ISSUE THREAD

**Issue by SpeedZDev** [h8man/NavMeshPlus#150]
so i followed the updated instructions in the repo on how to get started and everything is set but when i hit bake i cant see the blue path when hitting bake in 2d.

![image](https://github.com/h8man/NavMeshPlus/assets/98675043/493eb29d-f6d9-4d78-ad13-a02622ea0336)
![image](https://github.com/h8man/NavMeshPlus/assets/98675043/84ea0b25-9b6d-4301-8ef4-0bcc91f34db3)
![image](https://github.com/h8man/NavMeshPlus/assets/98675043/f5e9f63f-a263-4aa8-92db-936c202eb164)
![image](https://github.com/h8man/NavMeshPlus/assets/98675043/ec7a8ba9-374c-4b20-87bb-edc92442cc7f)
![image](https://github.com/h8man/NavMeshPlus/assets/98675043/549a8898-82f9-4824-9f11-151327764205)

Ive tried everything and i did exactly as the repo said but the blue for when i hit bake doesn't work.

**Comment by ziplock9000** [comment]
I had this same issue, setting the NavMesh object to static fixed it for me.

**Comment by SpeedZDev** [comment]
> I had this same issue, setting the NavMesh object to static fixed it for me.
I Still have the same issue where the blue doesn't appear but it clearly detects sources.Have Any Other tips?
![image](https://github.com/h8man/NavMeshPlus/assets/98675043/9a69e3c5-3a7e-431d-934e-705625600fea)

**Comment by SpeedZDev** [comment]
Oh I notice it creates a border when i hit bake but i still cant see the blue

**Comment by DasicPhilipp** [comment]
Confirm this issue. Have exactly the same problem. It won't work in my own project, but works fine in the demo. Gizmos are enabled

**Comment by h8man** [comment]
@SpeedZDev

You marked ground as not walkable, so there nowhere to walk, remove modifier and bake again. It is explained in https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#mazes

Start from easy setup, makes yourself comfortable with tools, after that try more complex cases.

**Comment by SpeedZDev** [comment]
Ok thanks man it works

**Comment by h8man** [comment]
If there any suggestions on wiki improvements, please leave a comment
