### ISSUE TITLE
Updating NavMesh data doesn't work properly

### ISSUE THREAD

**Issue by DasicPhilipp** [h8man/NavMeshPlus#151]
I use NacMeshModifiers on my tilemap. When I press the "Bake" button, it throws an exception though it bakes sources successfully. Anyway, the blue rectangle you seed doesn't match the tilemap size and just takes all screen space
![image](https://github.com/h8man/NavMeshPlus/assets/66508993/855de399-3353-488a-8e74-88eac562ca90)

**Comment by h8man** [comment]
@DasicPhilipp

1. Show me debug logs from console and tilemap in the scene
2. You used "Override by grid", so 2d objects are replaced with boxes (now quads)

I have no idea how builder found any quads in the scene, except when you using 3d objects.

_A note: NavMesh Plus should support mixed use_

**Comment by DasicPhilipp** [comment]
@h8man 

Debug logs:
(Filename: ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Scripts/CollectSources2d.cs Line: 51)

To World Bounds: Center: (17.00, 0.00, 2.50), Extents: (49.00, 0.00, 14.00)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
NavMeshPlus.Extensions.CollectSources2d:CalculateGridWorldBounds (NavMeshPlus.Components.NavMeshSurface,UnityEngine.Matrix4x4,UnityEngine.Bounds) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Scripts/CollectSources2d.cs:52)
NavMeshPlus.Extensions.CollectSources2d:CalculateWorldBounds (NavMeshPlus.Components.NavMeshSurface,System.Collections.Generic.List`1<UnityEngine.AI.NavMeshBuildSource>,NavMeshPlus.Extensions.NavMeshBuilderState) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Scripts/CollectSources2d.cs:33)
NavMeshPlus.Components.NavMeshSurface:CalculateWorldBounds (System.Collections.Generic.List`1<UnityEngine.AI.NavMeshBuildSource>) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Scripts/NavMeshSurface.cs:428)
NavMeshPlus.Components.NavMeshSurface:UpdateNavMesh (UnityEngine.AI.NavMeshData) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Scripts/NavMeshSurface.cs:228)
NavMeshPlus.Editors.Components.NavMeshAssetManager:StartBakingSurfaces (UnityEngine.Object[]) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Editor/NavMeshAssetManager.cs:127)
NavMeshPlus.Editors.Components.NavMeshSurfaceEditor:OnInspectorGUI () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs:264)
UnityEditor.UIElements.InspectorElement/<>c__DisplayClass72_0:<CreateInspectorElementUsingIMGUI>b__0 ()
UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,bool)
UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase,bool,bool)
UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI (UnityEngine.UIElements.EventBase,bool,bool)
UnityEngine.UIElements.IMGUIContainer:ProcessEvent (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEvent (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,bool)
UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:ProcessEventQueue ()
UnityEngine.UIElements.EventDispatcher:OpenGate ()
UnityEngine.UIElements.EventDispatcherGate:Dispose ()
UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:Dispatch (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,UnityEngine.UIElements.DispatchMode)
UnityEngine.UIElements.BaseVisualElementPanel:SendEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.DispatchMode)
UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel)
UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (int,intptr,bool&)
UnityEngine.UIElements.UIEventRegistration:ProcessEvent (int,intptr)
UnityEngine.UIElements.UIEventRegistration/<>c:<.cctor>b__1_2 (int,intptr)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

(Filename: ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Scripts/CollectSources2d.cs Line: 52)

RuntimeNavMeshBuilder: Source mesh Quad has invalid vertex data and will be skipped.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.AI.NavMeshBuilder:UpdateNavMeshDataAsyncListInternal (UnityEngine.AI.NavMeshData,UnityEngine.AI.NavMeshBuildSettings,object,UnityEngine.Bounds)
UnityEngine.AI.NavMeshBuilder:UpdateNavMeshDataAsync (UnityEngine.AI.NavMeshData,UnityEngine.AI.NavMeshBuildSettings,System.Collections.Generic.List`1<UnityEngine.AI.NavMeshBuildSource>,UnityEngine.Bounds)
NavMeshPlus.Components.NavMeshSurface:UpdateNavMesh (UnityEngine.AI.NavMeshData) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Scripts/NavMeshSurface.cs:235)
NavMeshPlus.Editors.Components.NavMeshAssetManager:StartBakingSurfaces (UnityEngine.Object[]) (at ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Editor/NavMeshAssetManager.cs:127)
NavMeshPlus.Editors.Components.NavMeshSurfaceEditor:OnInspectorGUI () (at ./Library/PackageCache/com.h8man.2d.navmeshplus@4f4966ff65/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs:264)
UnityEditor.UIElements.InspectorElement/<>c__DisplayClass72_0:<CreateInspectorElementUsingIMGUI>b__0 ()
UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,bool)
UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase,bool,bool)
UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI (UnityEngine.UIElements.EventBase,bool,bool)
UnityEngine.UIElements.IMGUIContainer:ProcessEvent (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEvent (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,bool)
UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:ProcessEventQueue ()
UnityEngine.UIElements.EventDispatcher:OpenGate ()
UnityEngine.UIElements.EventDispatcherGate:Dispose ()
UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:Dispatch (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,UnityEngine.UIElements.DispatchMode)
UnityEngine.UIElements.BaseVisualElementPanel:SendEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.DispatchMode)
UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel)
UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (int,intptr,bool&)
UnityEngine.UIElements.UIEventRegistration:ProcessEvent (int,intptr)
UnityEngine.UIElements.UIEventRegistration/<>c:<.cctor>b__1_2 (int,intptr)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)


And the tilemap:
![image](https://github.com/h8man/NavMeshPlus/assets/66508993/49240736-b2f8-4e9e-b458-7d0590897470)

**Comment by DasicPhilipp** [comment]
> 2. You used "Override by grid", so 2d objects are replaced with boxes (now quads)
> 
> I have no idea how builder found any quads in the scene, except when you using 3d objects.

I don't use any 3D objects. The option "Override by grid" doesn't change anything, it gives the same exception

**Comment by h8man** [comment]
Try to Add NavMesh RootSources2d to gameobject with Navigation Surface. Put tilemap as only root and bake.
It should ignore other gameobjects except your tilemap and its child objects.

**Comment by DasicPhilipp** [comment]
Thank you, it seems to be a solution. I've also discovered that UI Layers may be the source of the issue, so it is better not to include them.

However, my navmesh still looks a little bit weird. There are too many gaps between meshes, is there is a way to make it close to the tilemap walls?
