### ISSUE TITLE
Problem with navigation straight down or up

### ISSUE THREAD

**Issue by Simone98** [h8man/NavMeshPlus#152]
I'm assigning a Transform to an object, and then use the Update to assign the target of the NavMeshAgent. The problem occurs when I have the target at the same X of the NavMesh agent. It stutters a lot and barely move towards the target. To reproduce i simply used this: 
`agent.SetDestination(transform.position + Vector3.up * 4);`

I thought about adding a simple offset to pass trought this bug, but if the target it's really far, than it could reach the same X position and the bug wouldn't be fixed.

**Comment by h8man** [comment]
Nice)
