### ISSUE TITLE
Agent stuck in invisible area

### ISSUE THREAD

**Issue by Peristero65** [h8man/NavMeshPlus#153]
Hello, I am a bit new to unity, but I followed the steps to add NavMeshPlus to this 2d prototype and it seems like it's not creating a mesh correctly. I see an outline around the tilemap but none of the blue lines or anything and the agent is confined to a small area. the area opens up a bit when I remove the walls but it still cant get close to the edge of the tilemap. I'll take any suggestions for why this might not be working
https://github.com/h8man/NavMeshPlus/assets/95777309/cc3b5038-b939-4215-894c-de1dd1e03f85

**Comment by h8man** [comment]
I don't see navigation map. Did you click Bake? What is in debug logs?

**Comment by Peristero65** [comment]
I'm guessing what you mean by nav map is the navmesh? there is a square around my tiles but no blue lines. I did click bake and follow the steps in the tutorial. After enabling the debugger it gives around 12 warnings in different places that say, "warning CS0618: 'NavMeshVisualizationSettings.showNavigation' is obsolete: 'showNavigation is no longer supported and will be removed.'" Another thing to mention is that I am using Unity 2022.3.1f1

**Comment by h8man** [comment]
I used latest version. Found no problems https://github.com/h8man/NavMeshPlus/issues/154
Check demo https://github.com/h8man/RedHotSweetPepper

**Comment by h8man** [comment]
NavMeshPlus updated with consistent component naming "Navigation XXX", was tested with latest Unity LTS 2022.3.4. Also Wiki had minor updates.
