### ISSUE TITLE
issue with latest LTS

### ISSUE THREAD

**Issue by drizztdourden08** [h8man/NavMeshPlus#154]
Hi,

I've been using your library for a very long times and loving it.

Though the last few month with it have been rougher, basically everytime I upgrade unity version. :)

This times to latest LTS and planning to stay until release. I can't seem to getting it working somehow. Have you tried with his last version? It wasn't working in my actual project (I had the prior version where both Navigation AI from unity and your library needed to be mixed up for it to work properly) I think it was only this version (or at least I don't see any mention about this anywhere else)

I have created a brand new project and installed the library, only yours.

Added a "floor" with a basic white square sprite
added two "walls" with two other basic red square sprite.

both of them have modifier on them, one overide walkable, the other 2 not walkable

added the navmesh with the collect source 2d. rotate then bake.

nothing happens. at least it doesn't detect the sources it seems... says source 0
![image](https://github.com/h8man/NavMeshPlus/assets/36481532/e66244cb-153a-4bec-9758-e35041caad86)

In my actual project, i kept the setup I had which uses tilemap instead. and this gives me the right amount of sources. note that this is generated by code and refresh at certain point. the refresh doesn't return an error message but it's like the mesh isn't there... here what a map could look like (Procedurally gen..).
![image](https://github.com/h8man/NavMeshPlus/assets/36481532/b19945da-0162-42ac-86b4-798336c7b443)
![image](https://github.com/h8man/NavMeshPlus/assets/36481532/88d119de-561c-4da4-9e1a-2c21db1f1711)
![image](https://github.com/h8man/NavMeshPlus/assets/36481532/cbacf9a7-f81e-4a36-94b0-d4f40337fcf3)

With the exception of needing the unity AI package previously, it doesn't give any error message per say except that the agent isn't on a mesh...

and another thing. I'm not sure if it's me but maybe the mesh is there but I can't see the debug bake? I know I had issue seeing the debug mesh in the past.

**Comment by drizztdourden08** [comment]
Also, not sure how to read the logs generated to know if a real mesh has been genrated or not. what are the numbers exactly and how to make sense of them?

**Comment by h8man** [comment]
I will check LTS

**Comment by h8man** [comment]
I don't know, I used latest LTS on demo - It works. I see you are using Physics collider with tilemap and in demo. Are you have colliders? Maybe you want tot use render meshes?
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/7bf033cb-5edf-4e36-88a7-e7b960f4c053)

**Comment by drizztdourden08** [comment]
@Positivex Interesting.

I’ll try myself tonight. I didn’t think to try the demo at all during my testing personally and went straight for a nee project, which might be what happened here and why there is a difference between my results and @h8man one.

I’ll try with the demo on my side tonight just to confirm as well if I find the times, otherwise tomorrow.

**Comment by h8man** [comment]
I tested again, created new object, added new components and bake. It works in LTS 2023.3.4f1
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/6c712100-fbf3-4d4c-9c44-252387d3d0ef)

**Comment by pranagrinders** [comment]
I am trying right now to make the base project work and getting same error with positivex.
NevMeshExtension requires a NavMeshSurface component
 m_navMeshOwner = GetComponent<NavMeshSurface>();
 this code is for      class NavMeshPlus.Components.NavMeshSurface
 but we need to reference NavMeshSurface from UnityEngine.AI  i think

**Comment by h8man** [comment]
Sorry, I missed a video. Add surface first, collect2d second. When you adding collect2d  it registers its extensions inside surface.

**Comment by h8man** [comment]
if there is an ability to handle those cases in Unity (to reregister extension), please point me out.

**Comment by h8man** [comment]
@drizztdourden08 several people confirmed that NavMeshPlus works with LTS. So the issue with a setup. Share full logs and simple scenario that you want to cover

**Comment by drizztdourden08** [comment]
Yes. I just retested and the order was in fact the issue in my testing in the second project. this definitly seems to work just fine with LTS. thanks

However, I can't make it work in my full project still. I seems to get the baking (At runtime) doing just fine but I still get the error message from the agent being too far from the mesh but it is directly on it. 
![image](https://github.com/h8man/NavMeshPlus/assets/36481532/dfa01322-91f6-4e1c-ae18-c5efed156239)

I DO NOT have the baking "debug" gizmo appearing at all in unity. I have no clue why and this makes it very hard to know if the bake was succesful for real at runtime or not. I can just see the log themselves. My project, the demo or a brand new project. (any idea?)

The logs are very weird by themselves. It seems to be detecting over 4000+ sources after I generate the map somehow. There's only two tilemap in all of this (Which are the 2 first source we see), and after the generation, the tilemap are filled with... well... tiles. how it goes to that type of number, I don't know.
![image](https://github.com/h8man/NavMeshPlus/assets/36481532/bca33fff-a908-41c6-9d2f-3391ec850c26)

I read on a forum post that nav mesh error might be a memory issue and if it really has 4000+ source, that might make sense. but where would that's be coming from, I don't know.

Just to be thorough, here's the code in which the runtime bake runs (not directly there but to show it runs in a coroutine):

     private IEnumerator InitializeGameMap() {
            yield return new WaitForSeconds(0.5f);

            // Generate the map
            yield return PrepareMap();

            // Generate starting positions
            FindStartingPosition();
            yield return PlacePaths();

            // Generate all shadow on the map
            yield return CastShadows();

            // Generate the navmesh
            yield return GenerateNavMesh();

            // Activate Camera
            Camera.main.GetComponent<CinemachineBrain>().enabled = true;

            // Create all actors for the players
            CreatePlayerObjects();

            Core.i.session.CurrentLevel.MapReady = true;
        }

and the function itself:

      public IEnumerator GenerateNavMesh() {
            yield return new WaitForSeconds(0.1f);

            gameNavMesh.BuildNavMeshAsync();
            gameNavMesh.UpdateNavMesh(gameNavMesh.navMeshData);
            Debug.Log("navmesh built");
        }

nothing crazy as you can see. should be simple.

I tried running it with rendered and nothing changes. And the collider in physics mode are there just fine too.

**Comment by h8man** [comment]
gameNavMesh.BuildNavMeshAsync();
        gameNavMesh.UpdateNavMesh(gameNavMesh.navMeshData);

Call only of the methods. Can you bake without runtime? Try bake from Navigation Surface component during runtime

**Comment by pranagrinders** [comment]
Edit:
 Problem solved when i add an empty object, add a sprite renderer, add navigation modifier and scaled it so it covers the map to use as a walkable area.. 
 check override, walkable..
 
 so because there is no walkable area, it says its not on the map..
 what i assumed was that map does that :D

**Comment by pranagrinders** [comment]
> I am trying right now to make the base project work and getting same error with positivex. NevMeshExtension requires a NavMeshSurface component m_navMeshOwner = GetComponentNavMeshSurface; this code is for class NavMeshPlus.Components.NavMeshSurface but we need to reference NavMeshSurface from UnityEngine.AI i think
 Edit: Problem solved when i add an empty object, add a sprite renderer, add navigation modifier and scaled it so it covers the map to use as a walkable area.. check override, walkable..
 
 so because there is no walkable area, it says its not on the map.. what i assumed was that map does that :D

**Comment by drizztdourden08** [comment]
> ```
>     gameNavMesh.BuildNavMeshAsync();
>     gameNavMesh.UpdateNavMesh(gameNavMesh.navMeshData);
> ```
> 
> Call only one of the methods. Can you bake without runtime? Try bake from Navigation Surface component during runtime

I can bake without runtime. I get the same "kind" of result. in this screenshot where the game is not running, I get 281 sources.

and again, I can't see the gizmos for the baking process (the blue/black overlay) so it is hard for me to know if that actually worked or not.

removing the async line doesn't change much here. I'm still getting that it's not placing the agent on a navmesh, and I can't see the gizmos to actually see the calculated mesh.

**Comment by h8man** [comment]
@drizztdourden08 Any updates on issue? Is there anything I can do for you?

**Comment by drizztdourden08** [comment]
I've been on this for a few weeks and tried quite a bit of stuff. I'm sure this is probably a stupid mistake but I can't seems to find it at all.

I have found a few things that are actually different from before:
- When using the physics option, the walkable didn't need a collider and was (I think) probably considering everything as walkable
- My spawned enemies will now spawn outside the map unless I put the collider for my wall as trigger
- when set to istrigger, they spawn at the right place but still get me the error message I had before... and won't find the closest mesh
- However, when they're spawned, if I disable and reenable the mesh agent, it will start to find it way as normal.

I really don't get what's going on here. I feel like there an issue with the way physics option now works.

I'm continuing my troubleshooting but if you have any idea, please help. I'm kinda lost.

**Comment by h8man** [comment]
I can help you if you send me test project where I can reproduce issue. It is fastest way. But usually when people creates test project they able to find issue and resolve without me))
