### ISSUE TITLE
NavMeshAgent auto generate collider is rotated

### ISSUE THREAD

**Issue by 1174331877** [h8man/NavMeshPlus#156]
![image](https://github.com/h8man/NavMeshPlus/assets/30250246/2d9b5a3e-48b6-4d41-a3d6-1a24b4918b10)
in editor mode.
![image](https://github.com/h8man/NavMeshPlus/assets/30250246/7f707514-a174-4c04-833c-5144853cbb7f)
int runtime mode.
runtime collider shape is not expect.

**Comment by h8man** [comment]
NanMeshAgent is not a part of NavMeshPlus, its Unity native component
