### ISSUE TITLE
Y-axis movement doesn't work

### ISSUE THREAD

**Issue by IamBogdan** [h8man/NavMeshPlus#157]
The problem is shown in the video.

My code:
```C#
private void Update()
{
        _nmAgent.SetDestination(_target.position);
}
```

My settings:

![pic1](https://github.com/h8man/NavMeshPlus/assets/57235610/37a76de8-5384-49c4-9ccf-0fbc35553bdb)

![pic2](https://github.com/h8man/NavMeshPlus/assets/57235610/f58a7f55-9f72-4ef1-9aff-e15c0e8a72f9)

https://github.com/h8man/NavMeshPlus/assets/57235610/f24f02c2-ba35-4af0-91f1-a431503987bf

**Comment by h8man** [comment]
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/3de57547-b78a-4263-971f-fbb3d4d82bde)

**Comment by IamBogdan** [comment]
That helped, thank you very much!
