### ISSUE TITLE
Latest release does not bake using Physics Colliders, works fine otherwise

### ISSUE THREAD

**Issue by leowilbur110** [h8man/NavMeshPlus#159]
Thank you for this library btw, I've used it well in the past but now it doesn't work with the physics colliders :( 

Latest release does not bake using Physics Colliders, works fine using the render meshes.

I've tried adding the various components in specific order (per other issues I explored).

I also tried adding a composite collider 2d to a very simplified case with a single object and it still doesn't work. I also put the object inside my layout btw and it doesn't work.

I'm using 2021.2.19f1.

FYI I'm not using tilemaps or anything like that and your older libraries did work the way I intended.

One quick note: when I bake using physics colliders I see a strange grey outline show up but it does not bake and show the blue navigation mesh that I'm expecting with the physics colliders removed.

**Comment by h8man** [comment]
Latest release or 2021.2.19f1?

Colliders are supported only form #if UNITY_2019_3_OR_NEWER

**Comment by leowilbur110** [comment]
@h8man on no problem, will upgrade my project later. Thx!

**Comment by h8man** [comment]
reopen if needed
