### ISSUE TITLE
Game will not build with this package

### ISSUE THREAD

**Issue by KingDuck147** [h8man/NavMeshPlus#160]
The game does not build after installing this package.

The error that is thrown is:
Assets\NavMeshPlus-master\NavMeshComponents\Scripts\NavMeshSurface.cs(87,16): error CS0246: The type or namespace name 'NavMeshData' could not be found (are you missing a using directive or an assembly reference?)

There is about 65 of these errors all in different locations but all are related to the package.

Any help on how to fix this would be appreciated.

Thanks.

**Comment by h8man** [comment]
Cheking

**Comment by h8man** [comment]
What version of unity you are using? do you have navigation.AI installed?

**Comment by KingDuck147** [comment]
Unity 2021.3.10f1 Personal. I did not have navigation.AI installed so I installed it and I get the same error.

**Comment by KingDuck147** [comment]
> What version of unity you are using? do you have navigation.AI installed?

Just installed the current latest version of Unity, 2022.3.5f1, same error is occuring.

**Comment by h8man** [comment]
Sorry, I cannot fix issue as I cannot reproduce it. I'm able to build and run application with no problem.
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/c699eab0-4d57-4232-8d17-4da6d632bed5)

Did you tried fresh test project? can you refer to 'NavMeshData' from your scripts? It is standard Unity's class

**Comment by KingDuck147** [comment]
> Sorry, I cannot fix issue as I cannot reproduce it. I'm able to build and run application with no problem. ![image](https://user-images.githubusercontent.com/44724892/257046132-c699eab0-4d57-4232-8d17-4da6d632bed5.png)
> 
> Did you tried fresh test project? can you refer to 'NavMeshData' from your scripts? It is standard Unity's class

Fixed this by dragging the navmesh components file only from the zip file and not the whole thing. Probably something I should have done in the first place but atleast if this happens in the future, that is the solution.

Thank you for your help.
