### ISSUE TITLE
what to do if there is an error with NavMeshPlus

### ISSUE THREAD

**Issue by nikito2223** [h8man/NavMeshPlus#161]
Library\PackageCache\com.h8man.2d.navmeshplus@f8a1aedbf0\NavMeshComponents\Scripts\NavMeshSurface.cs(219,67): error CS1026: ) expected
I have already reinstalled 5 times what's the matter, my unity 2019

**Comment by h8man** [comment]
Have no idea. Also I cannot support unsupported Unity versions. There is nothing that can go wrong on line NavMeshSurface.cs(219,67)

What version of NavMeshPlus unity reporting to you?

**Comment by nikito2223** [comment]
unity's version? version: 2019.4.8f And if you're talking about a mistake, it's always

**Comment by h8man** [comment]
What version of NavMeshPlus are you using?
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/a341d9e4-6664-49eb-9e21-b75c52b1a473)

**Comment by nikito2223** [comment]
![Снимок экрана (6)](https://github.com/h8man/NavMeshPlus/assets/107321123/27f19bab-df13-480d-b24b-20d2841c0f32)
![Снимок экрана (7)](https://github.com/h8man/NavMeshPlus/assets/107321123/3cc26fb5-866f-46c8-834e-b05160bd0991)
Good

**Comment by h8man** [comment]
That is changes everything))

_Unity support for C# 8 has started on version 2020.2 and C# 9 has started on version 2021.2._

So its because of new 'using' statement. You either can use newer Unity or change package code, the deal is in curly brackets 

https://csharp.christiannagel.com/2019/04/09/using/

**Comment by nikito2223** [comment]
And how to redo it?

**Comment by nikito2223** [comment]
can you give an example

**Comment by h8man** [comment]
This code
` public void BuildNavMesh()
        {
            using var builderState = new NavMeshBuilderState() { };

            var sources = CollectSources(builderState);

            // Use unscaled bounds - this differs in behaviour from e.g. collider components.
            // But is similar to reflection probe - and since navmesh data has no scaling support - it is the right choice here.
            var sourcesBounds = new Bounds(m_Center, Abs(m_Size));
            if (m_CollectObjects == CollectObjects.All || m_CollectObjects == CollectObjects.Children)
            {
                sourcesBounds = CalculateWorldBounds(sources);
            }
            builderState.worldBounds = sourcesBounds;
            for (int i = 0; i < NevMeshExtensions.Count; ++i)
            {
                NevMeshExtensions[i].PostCollectSources(this, sources, builderState);
            }
            var data = NavMeshBuilder.BuildNavMeshData(GetBuildSettings(),
                    sources, sourcesBounds, transform.position, transform.rotation);

            if (data != null)
            {
                data.name = gameObject.name;
                RemoveData();
                m_NavMeshData = data;
                if (isActiveAndEnabled)
                    AddData();
            }
        }`

Become

` public void BuildNavMesh()
        {
            using( var builderState = new NavMeshBuilderState() { })
           {

            var sources = CollectSources(builderState);

            // Use unscaled bounds - this differs in behaviour from e.g. collider components.
            // But is similar to reflection probe - and since navmesh data has no scaling support - it is the right choice here.
            var sourcesBounds = new Bounds(m_Center, Abs(m_Size));
            if (m_CollectObjects == CollectObjects.All || m_CollectObjects == CollectObjects.Children)
            {
                sourcesBounds = CalculateWorldBounds(sources);
            }
            builderState.worldBounds = sourcesBounds;
            for (int i = 0; i < NevMeshExtensions.Count; ++i)
            {
                NevMeshExtensions[i].PostCollectSources(this, sources, builderState);
            }
            var data = NavMeshBuilder.BuildNavMeshData(GetBuildSettings(),
                    sources, sourcesBounds, transform.position, transform.rotation);
            }
            if (data != null)
            {
                data.name = gameObject.name;
                RemoveData();
                m_NavMeshData = data;
                if (isActiveAndEnabled)
                    AddData();
            }
        }`

**Comment by nikito2223** [comment]
Good
