### ISSUE TITLE
Error Null

### ISSUE THREAD

**Issue by ImperialCrise** [h8man/NavMeshPlus#163]
I encountered the following error (see attached image) while attempting to bake a NavSurface, wherein a Prefab contains a NavigationModifier that overwrites the walkable state.

Version Nav: 0.2.18
Version Unity : 2023.2.0b2
Version AI Navigation: 2.0.0-pre.3 (RC)

![image](https://github.com/h8man/NavMeshPlus/assets/16134489/1a093899-4d03-40e0-ac09-0d15d6fb0550)

![image](https://github.com/h8man/NavMeshPlus/assets/16134489/971ff985-ff83-4079-83e7-2157f101ce2d)

**Comment by h8man** [comment]
No response
