### ISSUE TITLE
How can users who are still using NavMeshPlus v0.1.0 update on 2022.3.4f1

### ISSUE THREAD

**Issue by determinationlove** [h8man/NavMeshPlus#164]
Hi, I was originally using 2019.4.40f1 & NavMeshPlus v0.1.0

Later, I upgraded the project to 2022.3.4f1 and found that some functions related to NavMesh failed
So I think I should also upgrade the NavMeshPlus package
I downloaded this git repo and replaced all the contents of the "NavMeshPlus-master" folder in my project with the new version
But when I opened Unity again, I found that all the Components related to NavMesh were missing

How can users who are still using NavMeshPlus v0.1.0 update on 2022.3.4f1?

I think it was a devastating decision that I did not install using the git URL in the first place...

**Comment by h8man** [comment]
Due to Unity update we were forced to change naming and meta files. So after update all components are shown as missing.
Now all components has prefix "Navigation -", also wiki is recently updated.

**Comment by h8man** [comment]
Redo the work, names and API has been changed
