### ISSUE TITLE
NavMeshAgent.Move not working with vertical vector

### ISSUE THREAD

**Issue by michaelSchrier** [h8man/NavMeshPlus#165]
For some reason, if you supply a vector to NavMeshAgent.Move that has no x value (just y), it doesn't move. I can provide x values as low as 0.00001 and it'll work fine, but anything lower, or 0, will not result in movement. 

This has similarly been reported here: https://forum.unity.com/threads/navmesh-agent-the-y-next-position-y-velocity-does-not-update-if-there-is-no-x-velocity.953465/

**Comment by h8man** [comment]
https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#known-issues

Just tilt your navmesh (I'm not using Agents at all)

**Comment by michaelSchrier** [comment]
> 

The tilting unfortunately didn't work for me :(

Also are you using your own Agent solution? Would this still need me to tilt the Nav Mesh? It seems this is an issue with specifically Unity's implementation and how it treats movement in just the Y as "directly up" in 3D space and ignores it.

**Comment by h8man** [comment]
1. I'm not sure why. Tilt was discovered by community and helped a lot of people.
2. I'm using static NavMesh methods to find a path. Without Agent you totally loosing local obstacle avoidance. When I will implement good obstacle avoidance I will release the code.
3. Seems plausible. Just drift on Z, nobody will se it) I need to test it before including into wiki
