### ISSUE TITLE
Relationship to AI Navigation package

### ISSUE THREAD

**Issue by michaelSchrier** [h8man/NavMeshPlus#166]
It seems that development of the initial repo this was forked from has ceased, and was turned into the following package.

https://docs.unity3d.com/Packages/com.unity.ai.navigation@1.1/manual/index.html

Is there any plan to update so this more readily supports the package? Having both NavMeshPlus and AI Navigation in my projects causes duplicate classes from the looks of it.

**Comment by h8man** [comment]
Hello. Yes initially it was fork. But:

1. Naming is different "Navigation" vs "Nav Mesh"
2. All meta files has different UIDs
3. It is tested and confirmed by multiple people that packages doesn't cause conflicts
4. Yes, classes are duplicated, use only one package at a time

Do I have plans to support and develop the package? Yes. Would I able to update and more readily supports the package? No, but open source can be done in collaboration. I'm accepting pull requests.

I would glad to work with ai.navigation, but it is not extensible in design and closed source (at least I cannot find official code for package).
