### ISSUE TITLE
Missing Gizmos Icons

### ISSUE THREAD

**Issue by zzxiang** [h8man/NavMeshPlus#17]
Some scripts in `NavMeshComponents\Scripts` are referencing missing icons, which seems to be in https://github.com/h8man/RedHotSweetPepper/tree/master/Assets/Gizmos .

**Comment by h8man** [comment]
Yes, those gizmos are not in this project.
Should I add them or remove references?

**Comment by zzxiang** [comment]
I like those icons, so I wish they could be added.

**Comment by h8man** [comment]
I decided to not add gizmos. Instead use RedHotSweetPapper with all extras and gismos from there. I will keep all in sync and up to date

**Comment by h8man** [comment]
Added
