### ISSUE TITLE
How to prevent huge monsters from getting stuck?

### ISSUE THREAD

**Issue by oovm** [h8man/NavMeshPlus#172]
I have many monsters of different sizes, among which the boss monster is more than 6 times the size of the smallest monster.

I encountered a problem where small monsters can pass, large monsters will get stuck. 

How should I make the large monsters go around instead of passing through narrow gaps?

![image](https://github.com/h8man/NavMeshPlus/assets/17541209/c03158c6-a661-46b2-b98c-4fedcf5dfedb)

I adjusted this value to large but it still didn't work.

**Comment by h8man** [comment]
You need an Agent for EACH size and the same number of navmeshes.

**Comment by oovm** [comment]
Fine, this does work.
