### ISSUE TITLE
2D NavMeshAgent gets stuck trying to move straight up or down

### ISSUE THREAD

**Issue by R0binicus** [h8man/NavMeshPlus#174]
Hi, 
I want to report an issue I found when an agent tries to move to a destination that is straight up or down in relation to the agent (has the same x position). The agent appears to not move for a few seconds, then occasionally jolts in the direction of the destination, and then stops moving for a while again. If the destination or agent is offset from the identical x position by at least 0.001 (from any source), the issue is no longer present. The issue is also NOT present for agent-destination pairs with the same y position.

Someone else seems to have experienced a similar issue on the unity forums but with no solutions: https://forum.unity.com/threads/2d-navmeshagent-will-not-move-straight-up-or-down-and-other-strange-behavior.1269635/

**Comment by h8man** [comment]
https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#known-issues

**Comment by h8man** [comment]
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/3270f560-ecdf-44cf-8976-cf29f0a7e337)

**Comment by h8man** [comment]
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/af530f67-c0b8-4b05-aa8b-d191684d638b)
