### ISSUE TITLE
Overlapping Walkable on top of Obstacle won't work..

### ISSUE THREAD

**Issue by SauronDark** [h8man/NavMeshPlus#176]
**What Happened?:**
generated navmash not considering walkable sorting layer sprite on top of obstacle object, for the reference see the images below 
![before](https://github.com/h8man/NavMeshPlus/assets/147647006/a01725cc-a26e-4629-9cee-cb3a6e7bc7c0)
![after](https://github.com/h8man/NavMeshPlus/assets/147647006/53544550-8192-4167-a2c7-bd620eb6354e)

**What I have Tried?**
- clear and bake after enabling walkable object
- tried changing sorting order, "walkable Ground" is on 0, "Wall" on 1 and "Walkable Overlap" on 2, than bake
- tried changing z on "Walkable Overlap"

**What is Expected?:**
there should be a navmesh on top of orange "Walkable Overlap" object connecting inside and out side navmesh part

**Comment by h8man** [comment]
Obstacle doesn't respect layers. See https://docs.unity3d.com/ScriptReference/AI.NavMeshObstacle.html
If you talking abstract "obstacle", so you need to change default navmesh to nonwalkable 
https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#mazes

**Comment by SauronDark** [comment]
oh right sorry, by saying obstacle I meant for "Non Walkable" override on Wall sprite, but what I am trying to achieve is to place a "Walkable" on top of "Non Walkable", so I was expecting a connection between the outer wall and inside navmesh. I also tried setting the default to Nonwalkable and overriding ground and overlapping image to Walkable, but navmesh isn't bridging.

**Comment by h8man** [comment]
Non-walkable overrides any region, you should mark only walkable space instead
https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#mazes

Also check navmesh demo https://github.com/h8man/RedHotSweetPepper

**Comment by SauronDark** [comment]
> Non-walkable overrides any region

oh, that makes sense, so basically, it is not possible without carving pixels out of the wall's image sprite, maybe I should consider that at run time, thanks for the help.
