### ISSUE TITLE
netcode and navmeshplus

### ISSUE THREAD

**Issue by streamDragon** [h8man/NavMeshPlus#177]
i am wondering maybe i have problems in integrating the navmesh as it into my netcode project
is there a way to work this 2 together?

i got few errors  -0 here is one of them 
NevMeshExtension requires a NavMeshSurface component
UnityEngine.Debug:LogError (object)
NavMeshPlus.Extensions.NavMeshExtension:ConnectToVcam (bool) (at Assets/HAGGAI_STUFF/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshExtension.cs:48)
NavMeshPlus.Extensions.NavMeshExtension:OnScriptReload () (at Assets/HAGGAI_STUFF/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshExtension.cs:37)

**Comment by h8man** [comment]
What error is it? I'm not familiar with net code
