### ISSUE TITLE
NavMeshCollecSources2d script does not exist

### ISSUE THREAD

**Issue by amigax** [h8man/NavMeshPlus#179]
importing using giturl you get no files.

**Comment by h8man** [comment]
Just tested, it works
Unity 2022.2.1f1
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/b36f0136-4476-46e5-8735-12cc88ba78ab)

**Comment by amigax** [comment]
ok intresting, i had to do it manually. sorry.
