### ISSUE TITLE
Upgrading to 2022

### ISSUE THREAD

**Issue by 0xdeployer** [h8man/NavMeshPlus#181]
Hi I recently upgraded to 2022 from 2021. NavMeshSurface was moved from UnityEngine.AI and some things changed. For example BuildNavMeshAsync no longer exists within the NavMeshSurface class. Any recommendations in regards to updating?

**Comment by h8man** [comment]
Unity released UnityEngine.AI with NavMeshSurface as package, now we have namespace conflict. So namespace has been changed namespace NavMeshPlus.Components

Also component names changed from NavMesh to Navigation

**Comment by vazquez595654** [comment]
Same issue. When I bake, nothing happens. No representation of the navmesh, and hence I get the error stating that SetDestination can only be called on an active agent that has been placed on a NavMesh.

Also, your directions on the github don't match:

"Add "Navigation Surface" component to Empty Object and add NavMeshCollecSources2d component after."

That component no longer exist.

**Comment by h8man** [comment]
Exact version of Unity please.

**Comment by h8man** [comment]
![image](https://github.com/h8man/NavMeshPlus/assets/44724892/215b2c67-5783-465b-a1e4-4770f4a6a479)

I don't know. Pease share a test project
