### ISSUE TITLE
NavMeshAgent.SetDestination does not work

### ISSUE THREAD

**Issue by amaiyoru-vv** [h8man/NavMeshPlus#182]
While attempting to use this package, I was given the error ""SetDestination" can only be called on an active agent that has been placed on a NavMesh." I was following this tutorial, but I know that it's old and apparently there was some 2022 update, so how would I produce the same result as in the tutorial with the current version?

My code:
![navmesh issue code](https://github.com/h8man/NavMeshPlus/assets/127546520/16fcc652-eaba-4af5-970e-e400215ad187)

I just want to have one object that chases another.
Tutorial link if anyone wants to help: https://www.youtube.com/watch?v=W-NIYi1t16Q&ab_channel=TheZBillDyl

**Comment by h8man** [comment]
https://github.com/h8man/NavMeshPlus/issues/158

in what exact version it doesn't work?

**Comment by amaiyoru-vv** [comment]
I am currently using the 2022.2.20 version of unity for my project.

**Comment by amaiyoru-vv** [comment]
Thank you for the tutorial
