### ISSUE TITLE
Same tilemap can't have two different surfaces 

### ISSUE THREAD

**Issue by mashiro11** [h8man/NavMeshPlus#183]
Hey! First of all thanks for the asset! It sure is handy!

I have a base surface in which I want to create 2 different navMeshes, 1 for default agent and another for Large agent. To acchieve that I needed to create 2 different game objects, one for each navigation surface and had to create 2 copies of same tilemap, each one with it's own navigationModifier. That's because if same object has 2 different navigationModifiers, each one targeting different agent types, both navigation surfaces built are set to the same type (mostly the second navigationModifier type on the gameObject).

What I expected was to have a gameObject with a tilemap in which I could add any number of different navigationModifiers and they would be able to build the different surfaces.

**Comment by h8man** [comment]
It should work as you described, Ill add demo scene.

**Comment by h8man** [comment]
Added scene to a demo:
- 2 navmesh objects
- 2 tilemaps for different agents
- 1 tilemap with 2 navmesh modifiers

https://github.com/h8man/RedHotSweetPepper/blob/master/Assets/Scenes/SampleSceneMultiagent.unity.meta

Is it what you were looking for?

**Comment by mashiro11** [comment]
Thanks for the quick reply!
Yes! That was it! Looking now I messed with the NavigationModifier agent type selection.
Thanks!
