### ISSUE TITLE
[Bug] NavigationModifierTilemap missing AffectedAgents field

### ISSUE THREAD

**Issue by snarlynarwhal** [h8man/NavMeshPlus#186]
Hi, I have a tilemap and want to override certain tilemap tiles for different agents. I want to override Rock tiles to be not walkable for Walking Agents. But since NavigationModifierTilemap doesn't contain an AffectedAgents field, both NagivationModifiers collect sources from NavigationModifierTilemap.

![image](https://github.com/h8man/NavMeshPlus/assets/3300071/a4853475-7f1a-4a48-87b0-006485285a93)

**Comment by snarlynarwhal** [comment]
I came up with a temporary solution that works:

```cs
public class NavMeshModifierPlus : NavMeshModifier
{
    public NavMeshModifierTilemapPlus NavMeshModifierTilemap => navMeshModifierTilemap;

    [SerializeField] private NavMeshModifierTilemapPlus navMeshModifierTilemap;
}

public class NavMeshModifierTilemapPlus : NavMeshModifierTilemap
{
    public override bool TryGetTileModifier(Vector3Int coords, Tilemap tilemap, out TileModifier modifier)
    {
        if (TryGetComponent(out NavMeshModifierPlus navMeshModifier) && navMeshModifier.NavMeshModifierTilemap == this)
        {
            return base.TryGetTileModifier(coords, tilemap, out modifier);
        }
        modifier = new TileModifier();
        return false;
    }
}
```
However, the inspector now shows a list of ints instead of a dropdown for the affected agents: 
 
![image](https://github.com/h8man/NavMeshPlus/assets/3300071/a5ff763b-4eab-42df-ae91-dfe5b968c735)

**Comment by snarlynarwhal** [comment]
I made a commit to fix this:

https://github.com/h8man/NavMeshPlus/compare/master...snarlynarwhal:NavMeshPlus:master

Let me know how it looks and if you have any feedback.

**Comment by h8man** [comment]
Thank you. I appreciate any help.

Code seems to be straight forward. Thanks again.
