### ISSUE TITLE
Isometic grid issues doesn't fit

### ISSUE THREAD

**Issue by unitodev** [h8man/NavMeshPlus#188]
HELP me plz !! how to implement with isometic grid I try but it dosen't fit 
![image](https://github.com/h8man/NavMeshPlus/assets/118905626/59da8976-e876-4983-bdee-46948e57ac98)

**Comment by h8man** [comment]
Looks fine to me. What problem do you have?
https://github.com/h8man/RedHotSweetPepper here is some samples. It has iso too

**Comment by h8man** [comment]
Ah, now I see. You need to "compress bound" or set default area as "non-walkable"

**Comment by h8man** [comment]
no reply
