### ISSUE TITLE
Geometry - Physics Colliders Mode - not work with CompositeCollider2D

### ISSUE THREAD

**Issue by DungDajHjep** [h8man/NavMeshPlus#19]
if use CompositeCollider2D on tile layer, it cant generade NavMesh
![Capture](https://user-images.githubusercontent.com/10284601/71961845-d7472280-322a-11ea-91df-d3733d645d78.PNG)

**Comment by h8man** [comment]
Hello @DungDajHjep,

I assume you are using 2019.3 branch.
If you getting message $"{collider.name} mesh is null" there is nothing I can do,
as I'm getting mesh from native API, and have no control over it.

Put break point on Scripts/NavMeshBuilder2d.cs: 51 to verify results.

For more info You can read from this post https://forum.unity.com/threads/2d-navmesh-pathfinding.503596/page-3#post-4699100
and this one https://forum.unity.com/threads/2d-navmesh-pathfinding.503596/page-4#post-4883540

I encourage you to ask question to MelvMay, as this API is not well documented yet.
Also it would be great to attach image of collider shape.

**Comment by h8man** [comment]
@DungDajHjep 
I took a closer look and found that composite collider is messing with mesh.
If you remove composite collider it would work.

**Comment by h8man** [comment]
I made changes.
Please try it out
