### ISSUE TITLE
Enemy not moving after git push and pull in other computer

### ISSUE THREAD

**Issue by RFornaro** [h8man/NavMeshPlus#190]
Hello! Basically, things on git must have not gone according to plan, pretty much the entire scene got messed up, basically the AI is now standing still and not moving towards the patrol points that would normally work. I have set up an FOV script to detect the player and it works, it starts chasing the player arounds and even respects the walls (I am using tilemap). What are some common pitfalls I should check that I may be forgetting?

**Comment by h8man** [comment]
Sorry, I didn't get what is going on. Is demo doesn't work? Or its inside your project?

 _What are some common pitfalls I should check that I may be forgetting?_ - pay attention to naming, components have very similar names with unity AI package

**Comment by RFornaro** [comment]
Hello! Sorry for the late response, I meant in my project, I fixed it though, logic was kind of conflicting with itself
