### ISSUE TITLE
Problems with not being able to see the baked navmesh

### ISSUE THREAD

**Issue by h8man** [h8man/NavMeshPlus#193]
My primary issue is that I have problems with not being able to see the baked navmesh. I am using Unity 2023.2.16f1. I tried following the readme instructions, and various tutorials but nothing seemed to work - when I hit 'Bake' nothing would show up. I checked Gizmos were enabled, navigation tab showing, Navigation Surface selected, but no joy.

Then I tried the RedHotSweetPepper sample in 2021.3.29f1, and that worked fine. However, when I converted that to 2023.2.16f1, it also no longer worked.

**Comment by h8man** [comment]
I dug a bit deeper on this - I was thinking to try to render the mesh myself in the RenderGizmoSelected - then it occurred to me to check out how it works for built in NavMeshSurface. I discovered the AI Navigation package's NavMeshSurfaceEditor has some code for "UNITY_2022_2_OR_NEWER" which does this:

`navSurface.navMeshDataInstance.FlagAsInSelectionHierarchy();`

I tried adding that to NavMeshPlus's NavMeshSurface, but unfortunately that FlagAsInSelectionHierarchy method is internal and therefore not accessible. However, calling it via reflection does seem to do the trick:

```
[DrawGizmo(GizmoType.Selected | GizmoType.Active | GizmoType.Pickable)]
static void RenderBoxGizmoSelected(NavigationSurface navSurface, GizmoType gizmoType)
{
    var method = navSurface.navMeshDataInstance.GetType().GetMethod("FlagAsInSelectionHierarchy", BindingFlags.NonPublic | BindingFlags.Instance);

    method.Invoke(navSurface.navMeshDataInstance, new object[] { });
    RenderBoxGizmo(navSurface, gizmoType, true);
}
```
It's hacky, for sure, but at least I can see my navmesh now and debug other issues. Hope this is of use to someone, and that the problem can be resolved somehow in NavMeshPlus in the future (hopefully without hacky reflection calls!).

**Comment by behdadsoft** [comment]
Hi.
Unfortunately I have same problem after switch form unity 2021 to 2022.

What is NavigationSurface assembly reference in above method?

![Capture](https://github.com/h8man/NavMeshPlus/assets/8759818/d1a45aec-66e7-47ab-a172-7dfd4074fa34)

**Comment by h8man** [comment]
NavMeshPlus, I'm checking right now if I have bad reference

**Comment by behdadsoft** [comment]
**using NavMeshPlus.Components** already added but can't recognize **NavigationSurface**.

**Comment by h8man** [comment]
I have Navigation.AI and navmeshplus is the same project installed. Build and run works totally fine.
Try using NavMeshSurface = NavMeshPlus.Components.NavMeshSurface;

Chek if files are in place or try

**Comment by behdadsoft** [comment]
I reinstalled navmeshplus and error fixed. but the biggest problem is still exist, mean baking not work correctly. in picture below, part of the baked environment. While all the environment inside the green frame should be baked. I had this problem when I converted my project from unity 2021 to 2022 and tried bake my scene in new version.

![Capture](https://github.com/h8man/NavMeshPlus/assets/8759818/5e00d32a-97c0-4f72-894e-354d76afca8d)

**Comment by h8man** [comment]
Check components naming. Maybe you have mix of Navigation.AI and NavMeshPlus.
Also check what default area is and what you have in your modifiers.

**Comment by behdadsoft** [comment]
The components used are correct. I used **Navigation Modifier** for the floor and **Navigation Surface** for NavMesh. I made a new scene and test it again, Everything seems to be working fine. 
It seems that my project has a problem after converting to the new version of Unity.
Thank you for your help and time.
