### ISSUE TITLE
Navmesh Tilemap help wanted

### ISSUE THREAD

**Issue by switchCTRL** [h8man/NavMeshPlus#195]
Hi! 
I've been trying to get NavMeshPlus to work with Tilemaps for some time now. Unfortunately, I'm encountering some difficulties.
The mesh never looks as expected. I'm probably configuring something wrong.

My current setup is as follows:
Let´s say I have a `Grid` with 2 rectangular `Tilemaps`:
- Level 0 
- Level 1

<img width="421" alt="Bildschirmfoto 2024-04-30 um 13 39 04" src="https://github.com/h8man/NavMeshPlus/assets/7301984/fd90ca73-0a55-4552-87ca-eacf149b0130">
<img width="904" alt="Bildschirmfoto 2024-04-30 um 13 41 00" src="https://github.com/h8man/NavMeshPlus/assets/7301984/2e0302ac-80f7-4475-af8f-92d906c56edf">

My Tiles are custom rule tiles each with a custom physics body. I tried to set the `Use Geometry` to Colliders. Then I get this Mesh:
<img width="1506" alt="Bildschirmfoto 2024-04-30 um 13 45 19" src="https://github.com/h8man/NavMeshPlus/assets/7301984/9fe5d0ed-943c-4299-ae18-bb826804c12e">

If I set it to `Render Meshes` (which I think is not what I need because some tiles are "half" tiles) it looks like this:
<img width="1266" alt="Bildschirmfoto 2024-04-30 um 13 46 22" src="https://github.com/h8man/NavMeshPlus/assets/7301984/cecc82f9-6500-4bdc-aa87-9f2eb5b6cdf1">

In both cases the agents can run through the cliff of Level 1 which should not be possible. Is there a way to get multiple tile map layers to work?

**Comment by h8man** [comment]
You have navmesh modifier + tilemap modifier, but you need only one of them

**Comment by switchCTRL** [comment]
Thanks for the response and sorry for my late answer. 
The `NavMeshModifierTilemap` has `NavMeshModifier` as requirement. 
<img width="372" alt="Bildschirmfoto 2024-05-03 um 09 18 16" src="https://github.com/h8man/NavMeshPlus/assets/7301984/e27e8982-7e3b-4b1c-807e-e5193fa67548">
If I use only the `NavMeshModifier` in combination with `PhysicsColliders` I get the result from the first screenshot. I assume one cannot have both, using physics shapes and define specific tiles as walkable, fast walkable, water etc.?

What I want to achieve is that the layers of my tile map are walkable on their own. If I connect them with stairs or something similar one can travel from on layer to another. 
Like in this picture:
<img width="1137" alt="Bildschirmfoto 2024-05-05 um 12 51 11" src="https://github.com/h8man/NavMeshPlus/assets/7301984/552b13c5-c175-45f2-ac71-a056bb64f4e4">

where 
- Green is walkable
- Blue is water (later the character may be able to swim)
- Yellow is fast walkable
- The stairs connect layer 0 and 1 (without stairs the character should not be able to travel between these two layers).
Is a setup like this possible?

**Comment by h8man** [comment]
I'm very sorry, I check that from a code, and didn't notice modifier is used by builder.
So yes, Navigation Modifier is required with Modifier Tilemap.
Here is sample:
https://github.com/h8man/RedHotSweetPepper/tree/master/Assets/Scenes/SampleSceneTilemapModifier

Try this scene to get a feel on how to works, as documentation is not updated right now

As for layers, Navigation doesn't support layers in traditional sense, cause everything is projected into 1 navigation mesh.
