### ISSUE TITLE
Problem when importing package

### ISSUE THREAD

**Issue by Jorgee-sk** [h8man/NavMeshPlus#197]
Hi! I was importing the navmesh to a current project im developing and Im actually getting this error when trying to import the package 

![image](https://github.com/h8man/NavMeshPlus/assets/73257086/87bad87b-e6fd-43c0-878d-27dd7720e838)

![image](https://github.com/h8man/NavMeshPlus/assets/73257086/ce1bc369-508a-4261-8163-be8f7ef1a842)

At the beggining i thought it was my bad because of the compiler version but after updating to lastest version, it seems that the error is not getting fixed. 
I think this is a new method so i dont know if this is a bug or something,

**Comment by h8man** [comment]
Hi,
This lines added two weeks ago. I didn't find any issue.
What version of Unity and .NET are you using? Attach screens please.

**Comment by Jorgee-sk** [comment]
It's possible that, due to the older version of .NET im using, the type of the Previews variable may not be automatically detected when using the new syntax. 

I had found some info about type inference in newers versions and i dont know if maybe is related.

In newer versions of C#, the compiler can infer the type from the context in certain situations, allowing you to omit specifying the type after the new keyword if you use the var keyword. However, in older versions of C# or .NET, this type inference may not be possible

![image](https://github.com/h8man/NavMeshPlus/assets/73257086/4374bf8b-97b6-4d8c-bd2e-0524dbc7aee3)

**Comment by h8man** [comment]
Please check if it helps

**Comment by Jorgee-sk** [comment]
Yes! It's actually worked for me, thank you!
