### ISSUE TITLE
Error when selecting Navigation Surface object and no navmesh showing up

### ISSUE THREAD

**Issue by Invisible99** [h8man/NavMeshPlus#200]
When I add the package into my project I can't see the navmesh because the gizmo seems to be broken. 
I also see following error
`NullReferenceException: Object reference not set to an instance of an object
NavMeshPlus.Components.Editors.NavMeshSurfaceEditor.RenderBoxGizmoSelected (NavMeshPlus.Components.NavMeshSurface navSurface, UnityEditor.GizmoType gizmoType) (at Packages/com.h8man.2d.navmeshplus/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs:310)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
`

**Comment by h8man** [comment]
What version of unity you are using?

**Comment by Invisible99** [comment]
2021.3.34f1

**Comment by h8man** [comment]
Unity doesn't support this version, and I dropped support in package    
    "name": "com.h8man.2d.navmeshplus",
    "displayName": "NavMeshPlus",
    "version": "0.2.22",
    "unity": "2022.3",

You can revert latest changes in that particular spot.

**Comment by Invisible99** [comment]
Can't seem to make that work

**Comment by h8man** [comment]
Can you copy source revert changes in this file NavMeshComponents/Editor/NavMeshSurfaceEditor.cs from this commit:
https://github.com/h8man/NavMeshPlus/commit/dd2842a593ef27ad6fa60d953208346404517743#diff-917dddfccffca5419cc97ca5f144edfd0157a92803a63e8fda8571e8fdf6f11f

**Comment by Invisible99** [comment]
That worked thank you very much!

**Comment by ConanGentleman** [comment]
It methods won't work for me. version: 2021.3.14f1
