### ISSUE TITLE
Adjust curves and walk cell by cell

### ISSUE THREAD

**Issue by lucas-noronha** [h8man/NavMeshPlus#203]
Hi, I'm using this plugin to handle characters movementation, so far it's have been very usefull, so first, thanks for provide this!

Now, I have two questions about the configuration, first, in my tests the character goes out of the path in accentueded curves, I had tried to set angular speed and another configuration, but anything seems to work.

In second place, I'm trying to make my character walk cell by cell of the grid, and I don't know if this is possible with NavMesh or with this plugin - I started learn more about movimentation now, if possible can you explain how do that? 

Anyway, thanks for your job!

demonstration video about curves
https://github.com/h8man/NavMeshPlus/assets/11718830/8b30f245-8cf6-42aa-bb61-7c28891bef9d
![NavMeshConfig](https://github.com/h8man/NavMeshPlus/assets/11718830/83122517-d4c1-4f6f-8a08-535246f3a847)

**Comment by h8man** [comment]
Hello,

NavMesh Agent is unity native component, so you may find answers from unity forum.
Also, you can create your own Agent that with move by cells. Pathfinding by itself can be done with NavMesh classes. Agent only execute movement and dynamic obstacle avoidance.
