### ISSUE TITLE
Error when i try build my unity project

### ISSUE THREAD

**Issue by QzzyHate** [h8man/NavMeshPlus#204]
when i try to building my unity project, i got this errors(first screenshot). 
![QZ7XfGfRNbo](https://github.com/user-attachments/assets/4eae2929-aa42-4c66-a2fe-ed490d41c2be)
I think all of this because this error: 
Assets\Pathfiding\NavMeshPlus-master\NavMeshComponents\Scripts\CollectTilemapSourcesCache2d.cs(30,68): error CS0426: The type name 'SyncTile' does not exist in the type 'Tilemap'

This error reference to this part of the code(second screenshot).
![mXk-qUZadTs](https://github.com/user-attachments/assets/021941bb-10e2-4691-8683-5e447e329f03)

**Comment by h8man** [comment]
https://docs.unity3d.com/ScriptReference/Tilemaps.Tilemap.SyncTile.html It should work. Unity version is 2022.3. And it seems part of engine.

What version of unity you are using?

**Comment by QzzyHate** [comment]
My unity version is 2021.3.38f1.  Tomorrow I will try what you recommended and tell about the result.
