### ISSUE TITLE
Agent not moving or getting stuck in nothing

### ISSUE THREAD

**Issue by GaLzZy** [h8man/NavMeshPlus#206]
I spawn agents on my nav mesh and then set their destination to a point in an array of points. The spawning of the minions looks like this:

```cs
private void CreateMinion(PlayerNumber player, UnitSO unitData)
{
    Transform[] pathPoints = GetCurrentPlayerPaths((int)player);
    Transform spawn = player == PlayerNumber.Player1 ? P1CreepsSpawn : P2CreepsSpawn;
    GameObject newMinion = Instantiate(unitPrefab, new Vector3(pathPoints[0].position.x, spawn.position.y), Quaternion.identity);
    newMinion.GetComponent<Unit>().minionAttributes = unitData;
    newMinion.GetComponent<Unit>().player = (int)player;
    newMinion.GetComponent<Unit>().playerPath = pathPoints;
    newMinion.GetComponent<NetworkObject>().Spawn(true);
}
```
Then OnNetworkSpawn on the minions, I do this:

```cs
agent.updateRotation = false;
agent.updateUpAxis = false;
agent.speed = minionAttributes.MoveSpeed;

if (NavMesh.SamplePosition(playerPath[pointIndex].position, out NavMeshHit hit, 0.25f, NavMesh.AllAreas))
{
    Debug.Log($"NAV HIT BABY: {hit.position}");
    NavMeshPath path = new NavMeshPath();
    bool yep = agent.CalculatePath(hit.position, path);
    Debug.Log($"Path: {path.status} ({yep})");
    agent.SetDestination(hit.position);
}
```
And here's what it looks like when they spawn, and I set their destination (I Debug.DrawLine their path in red): https://gyazo.com/4454aa2018fe86dfca049ec6523bb344

https://gyazo.com/b83f8991a0bd773c97fd5cb7a869ce38

Also if the movement is not vertical it seems to be fine for some odd reason: https://gyazo.com/ef588d9579f8c85fedc6377c0335f2c2 As soon as they get into vertical movment sometimes they get stuck on I don't know what...

Do you have any idea of what is going on? :O

Thanks

**Comment by GaLzZy** [comment]
Is that what i'm talking about?

https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#known-issues

**Comment by h8man** [comment]
Yes. There is 3 options:
1) Don't use Agents
2) Add tilt to navmesh
3) Drift destination\agent

It is unity bug

**Comment by GaLzZy** [comment]
Yeah no I was wondering what the Tilt surface button was for and that fixed my problem! Thanks
