### ISSUE TITLE
Error with DrawBoundingBoxGizmoAndIcon Function

### ISSUE THREAD

**Issue by BiagioGavioli** [h8man/NavMeshPlus#210]
Hi, i've tried to import NavMeshPlus in Unity 2021.3.31f1 and say that miss DrawBoundingBoxGizmoAndIcon() function in NavMeshSurfaceEditor.cs

**Comment by h8man** [comment]
@BiagioGavioli I'm sorry, I have 0 QA time left. Please try again I made un update

**Comment by BiagioGavioli** [comment]
> @BiagioGavioli I'm sorry, I have 0 QA time left. Please try again I made un update

Thank you for your fast response.
If i'm able to do it i will try it in my timezone evening (CET).

**Comment by h8man** [comment]
no reply
