### ISSUE TITLE
The whole thing is broken

### ISSUE THREAD

**Issue by lyxerexyl** [h8man/NavMeshPlus#212]
The whole thing is broken. Everything is renamed (making all existing tutorials in the whole universe to be misleading). Components cant be added, without errors.
![image](https://github.com/user-attachments/assets/e1573e22-99a7-49f5-989b-167965561919)

**Comment by h8man** [comment]
![image](https://github.com/user-attachments/assets/f8059624-57a0-4061-bc0d-1c3adf7f5c0a)

I just tested. It works.

From what version your updating? There were breaking changes year ago or so

**Comment by h8man** [comment]
no reply
