### ISSUE TITLE
 Enemy is stuck in the Obstacle

### ISSUE THREAD

**Issue by bestravis** [h8man/NavMeshPlus#213]
Hi， Developer

 Enemy will always stuck in the Obstacle。 Without these obstacles andWalls, everything is fine

plz help me 

Wall Inspector
![wall](https://github.com/user-attachments/assets/a9910ac7-61df-4bbd-9f2a-7a3f5f981eec)
![GIF 2024-8-30 18-11-26](https://github.com/user-attachments/assets/92386a32-00aa-4f9e-8b61-66bed11127f4)

![GIF 2024-8-30 18-07-48](https://github.com/user-attachments/assets/dc9b4a1c-3e58-47fb-a2f1-edae4beda485)

![Snipaste_2024-08-30_17-58-44](https://github.com/user-attachments/assets/1ea19f54-2fa6-400d-a7db-45b32029e8b8)

**Comment by bestravis** [comment]
When Enemy stuck int the Wall , It has a little scintillation

**Comment by bestravis** [comment]
maybe I should use tilemap cover the obstacle , then bake.  :D

**Comment by h8man** [comment]
You have physics and navigation, they are not compatible with each other. Other problem is that agent is a circle, and you are using square collider. How it even will work in theory?

https://docs.unity3d.com/Packages/com.unity.ai.navigation@1.1/manual/MixingComponents.html

**Comment by h8man** [comment]
Only solution I can see - don't use navigation agent, query path and move your character via code manually.

**Comment by bestravis** [comment]
> When Enemy stuck int the Wall , It has a little scintillation

thanks ，I should google it first

**Comment by bestravis** [comment]
> Only solution I can see - don't use navigation agent, query path and move your character via code manually.

I'am using wasd key move my player, Only enemy using nav agent .  I will remove physics first . How can I keep my enemies not overlapping without physics

**Comment by bestravis** [comment]
This is enemy info
![image](https://github.com/user-attachments/assets/9ac807bd-81b1-4cb0-8dff-71334295c425)

Players are not use the agent
