### ISSUE TITLE
Weird NavMeshAgent behaviour when disabling rotation and upaxis

### ISSUE THREAD

**Issue by duronrulez** [h8man/NavMeshPlus#22]
Hey,

so for some reason the agent doesnt want to avoid the non walkable areas, despite having a valid navmesh.
Basically what im doing is, setting a destination that is below the object on the Y axis. It starts moving but then gets stuck on the non walkable areas.

Gif: https://imgur.com/8fhpCmE 

If i enable back rotation and upaxis it rotates properly around the object, but it messed up everything :D because the navmeshagent doesnt understand its on a 2d plane :)

Any clues how to solve this?

**Comment by h8man** [comment]
Hi @duronrulez ,

Thank you for a feedback. NavMeshPlus generates "native" Unity NavMesh via Unity API. On the GIF I don't see any issue with NavMesh, so there no issue related to NavMeshPlus.

While I see inconvenient behavior from NavMeshAgent, I don't know the cause. But you can ask question on Unity specific part of the forum https://forum.unity.com/forums/navigation.79/

But before that, check NavMeshAgent.path status, and draw its corners 
`
length = Path.GetCornersNonAlloc(waypoints);
DebugDrawPath(waypoints, length);

 public override void DebugDrawPath(Vector3[] waypoints, int  length)
        {
            for (int i = 1; i < length; i++)
            {
                Debug.DrawLine(waypoints[i - 1], waypoints[i], Color.blue);
            }
            if (length > 1)
            {
                Debug.DrawLine(waypoints[0], waypoints[1], Color.red);
            }
        }
`

**Comment by duronrulez** [comment]
Thank you for the swift response.

Ah, it seems because my sprites pivots are from bottom left it doesnt calculate the distance it needs to move without colliding with the impassable terrain.

**Comment by h8man** [comment]
Hi,

Change pivot or make sprite as child object and offset it where you want.
Also, Agents does not mix with Physics well:
https://docs.unity3d.com/Manual/nav-MixingComponents.html

**Comment by duronrulez** [comment]
Thanks, ill experiment a bit about this, moving the sprite offsets will cause the need to offset everything else too :(

But as you pointed out, this is not a problem due to the navmesh plus. Thank you for the help.

**Comment by duronrulez** [comment]
In the end i ditched the navmesh approach and did a simple A* implementation.
