### ISSUE TITLE
NavMeshAgent radius limited to 0.05

### ISSUE THREAD

**Issue by marcin0klusek** [h8man/NavMeshPlus#223]
Hi,

I have been working on a 2D game. I have tried changing NavMeshAgent's radius to 0.04, but Unity set the bottom limit to 0.05 (because of that I should change the sprite sizes)

Is there a workaround for this or is it possible to override the limit?

![navmesh_radius_limit](https://github.com/user-attachments/assets/6607cb3a-74be-4aa2-b40b-fac9be8b6d79)

Because of the limit, the baked nav mesh is not generated correctly.

**Comment by h8man** [comment]
Hello,

Agent is "native" to Unity, so NavMeshPlus will not help. I also never tried to set value close to zero, so I don't have any trick for you.
