### ISSUE TITLE
Agent not visible in the Scene but is Visible in the Game view

### ISSUE THREAD

**Issue by krupis** [h8man/NavMeshPlus#224]
Hello. First of all, great work on this package.
I have followed the guide:
https://www.youtube.com/watch?v=FtQhX-lmYEA&ab_channel=Rootbin
To set up NavMeshPlus.

Everything seems to be okay, apart from 2 issues:

1. **When I bake the NavMeshData, it covers larger area than my map:**
![image](https://github.com/user-attachments/assets/eb76bef1-5650-43d2-85d2-681d0ad0f264)
My Grid contains Floor and Obstacles as shown below:
![image](https://github.com/user-attachments/assets/6c49097d-8768-4b4f-aeba-e8d6bc1a2050)
![image](https://github.com/user-attachments/assets/caf7a6c5-f23f-4055-988d-19dd7361aba2)

What could be the reason for this?

2. **Enemy Sprite is not visible when I play the game. It is visible in the Game view but not visible in the Scene.**
I have created an enemy with a larger order in layer to ensure it is visible and added a Nav Mesh Agent with an Enemy script that sets the target position destination.

When I look at the Enemy Transform position when I play the game, the Z axis is set to -0.794:
![image](https://github.com/user-attachments/assets/d9b709e7-4046-4cf2-8cc9-ae0c670236b9)
but my Player is on Z axis 0.

If I set my player to Z axis lower than 0 (in the image below I have set it to -0.1), the Enemy sprite becomes visible:
![image](https://github.com/user-attachments/assets/b67993e0-9d97-458e-a93d-837ebe6855cb)

I do not fully understand how does changing player Z position from 0 to -0.1 fixes that. It does not seem like a reliable way to fix this, I would like to understand a little bit more about this issue and learn how to fix this properly.

**Comment by h8man** [comment]
Hello.

1. Try "Compress Bound" in CollectSoirces2d component
2. Agent controls the character, there are many options how to override it (few included in this package)

Also check the demo https://github.com/h8man/RedHotSweetPepper

**Comment by krupis** [comment]
> Hello.
> 
> 1. Try "Compress Bound" in CollectSoirces2d component
> 2. Agent controls the character, there are many options how to override it (few included in this package)
> 
> Also check the demo https://github.com/h8man/RedHotSweetPepper


Thanks for a quick reply. It is still not clear to me why the Enemy still hides behind the map in the Game view (is perfectly visible in the Scene view). And why does changing player Z axis have affect on this

**Comment by krupis** [comment]
I have found 2 ways to fix the Enemy hiding behind the map in Game view but still not sure why it happens:

1. Play around with Player Z axis
2. Play around with the Agent Base Offset

If Base Offset is set to anything higher than 0.61, it will not be visible in Game view:

![image](https://github.com/user-attachments/assets/3f19cf11-6f3c-45ca-bd21-cb710e7cc792)
![image](https://github.com/user-attachments/assets/936ef634-2e38-46f4-bf75-60cbaa67d714)

**Comment by h8man** [comment]
Agent is Unity native component, so there nothing I can help further.
