### ISSUE TITLE
when gameObject can't reach target destination when all path blocked(non-walkable)

### ISSUE THREAD

**Issue by ArdhenisAflah** [h8man/NavMeshPlus#226]
How to know or get feedback from NavMeshSurface when there is no path impossible to reach destination?

**Comment by h8man** [comment]
Can be called from static method or from Agent

https://docs.unity3d.com/6000.0/Documentation/ScriptReference/AI.NavMesh.CalculatePath.html
https://docs.unity3d.com/6000.0/Documentation/ScriptReference/AI.NavMeshPath.html

**Comment by ArdhenisAflah** [comment]
okay thanks
