### ISSUE TITLE
Is it possible to make this work with a sidescrolling platformer? 

### ISSUE THREAD

**Issue by EndySlay** [h8man/NavMeshPlus#23]
I took a look at the wiki and pdf and it seems that it only works as a topdown game, is there a way to make it work with a 2d platformer?

**Comment by h8man** [comment]
Hi,

I'm not aware of side-scrolling navigation systems. Even if you will bake as 2.5D plane (sprites on XY plane and navmesh on ZX), obstacle avoidance still would not work.

Short answer - I believe event if its makeable it is not feasible to utilize NavMesh

Here is my answer to similar question https://forum.unity.com/threads/2d-navmesh-sprite-and-mesh-renderer.868402/#post-5717356

Leave a comment on your point view on this topic, maybe I missed something.
