### ISSUE TITLE
NavMesh generated over non-existent tiles

### ISSUE THREAD

**Issue by D0uble-V** [h8man/NavMeshPlus#24]
Hi, thanks for this great asset. I recently noticed a bug where NavMesh would be generated in places where tiles don't exist. Steps to replicate:

1. Set up tilemap as per how-to guide
2. Select single tile or filled box brush
3. Paint with shift key selected (i.e. remove tiles) anywhere on the tilemap where there's no actual tiles
4. Bake the NavMesh

This is the result in my case (note that the green-isn area contains tiles beneath it and the blue area doesn't - that's where I removed tiles):

![image](https://user-images.githubusercontent.com/64854433/81086103-3bf35f00-8f37-11ea-8630-b1ee33b6a3de.png)

Please let me know if you'd like me to provide any additional information.

**Comment by D0uble-V** [comment]
Please disregard. This is actually related to Unity itself. For anyone looking, the issue and the solution are described here:

https://issuetracker.unity3d.com/issues/tilemap-dot-size-does-not-change-when-the-tiles-are-erased

**Comment by h8man** [comment]
Hi

Use "Compress Bounds" option on NavMeshSurface2d
