### ISSUE TITLE
Updating navmesh at Runtime

### ISSUE THREAD

**Issue by DatenThielt** [h8man/NavMeshPlus#25]
Good afternoon!

Firstly I just want to say thank you for this great tool!

I'm attempting to generate a bunch of boxes at run time,  Before run time, if I place a Navmesh obstacle on the boxes and hit carve,  the boxes carve out their area in real time,  The same thing happens if I bake the navmesh.

But if I try to create the boxes at run time,  Even if they have the Navmesh obstacle set to carve, the navmesh still generates over them.  Is there something I need to do to get it to update with the generated boxes?

I'm 99% sure this is my lack of knowledge of the  navmesh system in general.  

Any help would be appreciated 
Thanks!

**Comment by h8man** [comment]
Hello.

NavMesh Obstacle is a part of Unity NavMesh API, and there is nothing special to NavMeshPlus.
I believe you just missing some setting or checkboxes https://docs.unity3d.com/Manual/class-NavMeshObstacle.html

Hit play and verify that there is no difference between premade and runtime obstacle setting.

Maybe share print screen with a part of scene and settings, I will take a look

**Comment by DatenThielt** [comment]
Closing this!

I was being stupid!  For some reason I was instantiating them on a completely different Z level, of course they were not being detected by the nav mesh,  

Thank you again!
