### ISSUE TITLE
Tiles with ColliderType.None are included in obstacles (sources)

### ISSUE THREAD

**Issue by subGlitch** [h8man/NavMeshPlus#27]
I'm using ColliderType.Grid for wall tiles and navMesh is building for them correctly. But I also use ColliderType.None for decoration tiles which are not obstacles like grass or bushes or decoration continuation (like spikes) of wall tile in neighbor cell.

But CollectTileSources() method includes such tiles in sources.

Of course, I probably should keep such tiles in separate tilemap to avoid redundant iteration. But anyway, adding ColliderType.None tiles into sources feels wrong.

**Comment by h8man** [comment]
Hi,

You can bake composite **collider** for your tilemap, so collider will account ColliderType.None in first place and as result - navmesh too.

Should ColliderType.None be tolerated when you bake Geometry (Shape)? Debatable. And you already answered it. Using multiple Tilemaps or Layers are the way to go.

But I will consider your suggestion.
