### ISSUE TITLE
Weird navmesh artefacts

### ISSUE THREAD

**Issue by subGlitch** [h8man/NavMeshPlus#28]
I have weird navmesh artefacts. You can see them in the screenshot. I managed to fix them by adding a quad rotated (90, 0, 0) and referencing it in Use Mesh Prefab setting of the NavMeshSurface2d. I don't understand why this fixed the problem, but somehow it worked.

But for me this solution feels like just a workaround. I think there should be no artefacts in a first place.

P.S.: thanks you very much for such a great tool

![artefacts](https://user-images.githubusercontent.com/11411763/88451319-60881480-ce5e-11ea-8db0-1be0199b971b.png)
![no artefacts](https://user-images.githubusercontent.com/11411763/88451324-709ff400-ce5e-11ea-9538-7eee0ebdad93.png)

**Comment by h8man** [comment]
Hi,

I see dotted line, and bake setting Default Area - Walkable.
So first NavMeshPlus created huge box area as walkable, and than carves out unwalkable regions.
I assume that you sprite shape are not complete squares and have some gaps, and those gas are not carved out.

You can override tile shape by "Use Mesh Prefab", as you do.
Or, if your world is in square tiles, enable "Override by Grid".
Or, better use this scenario https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#baking-a-maze

Also, enable compress bounds, it will increase bake time, but also will delete excessive tiles.

**Comment by subGlitch** [comment]
> I assume that you sprite shape are not complete squares and have some gaps, and those gas are not carved out.

But does it matter? Because I use ColliderType.Grid, not ColliderType.Sprite.

**Comment by h8man** [comment]
Hi,

Yes, it does matter if you bake Geometry https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#used-geometry
NavMeshPlus does not tolerate tilemaps "ColliderType".
Unity have public API to get mesh form sprite, or mesh from collider, but not mesh from grid cell, or mesh from sprite physics shape. And we need that mesh.

As for code above, I assume there is a bug. If both "Override Grid" and "Use Mesh Prefab" are used, than "size" is overwritten and does not correspond to grid's cell size.
`var size = new Vector3(tilemap.layoutGrid.cellSize.x, tilemap.layoutGrid.cellSize.y, 0);`
and
` if (builder.useMeshPrefab != null)
            {
                sharedMesh = builder.useMeshPrefab.GetComponent<MeshFilter>().sharedMesh;
                size = builder.useMeshPrefab.transform.localScale;`

**Comment by subGlitch** [comment]
> `var size = new Vector3(tilemap.layoutGrid.cellSize.x, tilemap.layoutGrid.cellSize.y, 0);`

Yep, this works! Thanks!
