### ISSUE TITLE
navmesh going through tiles

### ISSUE THREAD

**Issue by laurentopia** [h8man/NavMeshPlus#3]
When the agent radius is set to 0.3 the navmesh goes through tiles even though composite colliders are water tight
![image](https://user-images.githubusercontent.com/26075468/48176316-50b05180-e2c4-11e8-8a71-24ddfe8dcb91.png)

![image](https://user-images.githubusercontent.com/26075468/48176330-63c32180-e2c4-11e8-95a1-db14b9d7d212.png)

**Comment by h8man** [comment]
Seems its a big issue. I will take a closer look, but I assume that it is NavMeshBuilder fault

**Comment by h8man** [comment]
Hey, found that y-value in a box source is causing the issue. Now its good

**Comment by laurentopia** [comment]
Great work h8man!
