### ISSUE TITLE
Using This For Commercial Project [Question]

### ISSUE THREAD

**Issue by GamesBySaul** [h8man/NavMeshPlus#31]
Hi,

Firstly thank you for this asset, it is a life saver and has helped me do a lot for my project.
Just wanted to ask, I did read your licence but wanted to clarify, is there no issues of using this for a commercial games project, would you like credits or anything?

Thanks!

**Comment by h8man** [comment]
Hi,

1. Yes, sure, you can use for commercial products and free to modify it. Here is tldr https://tldrlegal.com/license/mit-license

2. It is required to add license "... shall be included in all copies or substantial portions of the Software." as I do with original Unity license

But:
- There is no words saying it should be publicly displayed.
- Every package in ".\Library\PackageCache\" contain license, even the Unity ones, but non of them are transferred to build in "./bin"
- There is no way to check licensing on embedded devices

As summary I would say: make sure that license stay somewhere near source code, but don't bother to include it with/in binaries.

**Comment by GamesBySaul** [comment]
> Hi,
> 
> 1. Yes, sure, you can use for commercial products and free to modify it. Here is tldr https://tldrlegal.com/license/mit-license
> 2. It is required to add license "... shall be included in all copies or substantial portions of the Software." as I do with original Unity license
> 
> But:
> 
> * There is no words saying it should be publicly displayed.
> * Every package in ".\Library\PackageCache" contain license, even the Unity ones, but non of them are transferred to build in "./bin"
> * There is no way to check licensing on embedded devices
> 
> As summary I would say: make sure that license stay somewhere near source code, but don't bother to include it with/in binaries.

Thanks a lot, you're a great person for doing this!

I will make sure the licence is near the source code!
