### ISSUE TITLE
I have question about movable obstacle in NaveMeshSurface2D

### ISSUE THREAD

**Issue by YEOSEUNGMO** [h8man/NavMeshPlus#33]
Hello guy!
I use your asset very useful.
But, I have question about movable obstacle.
Some obstacle object is Instantiate at runtime.
How to bake NaveMeshSurface2D at runtime?

**Comment by h8man** [comment]
Hello @YEOSEUNGMO 

There are few approaches
Another https://forum.unity.com/threads/2d-navmesh-pathfinding.503596/page-5#post-6084279
