### ISSUE TITLE
Sprite with Polygon Collider 2D doesn't work with NavMeshModifier

### ISSUE THREAD

**Issue by mezz** [h8man/NavMeshPlus#34]
Hello, first of all thanks for the script!

# Context
The issue I have is that I have a big sprite for a building that uses a `Polygon Collider 2D` component because its collision does not exactly match its shape.

# Issue 
## Description
I tried adding a `NavMeshModifier` component to the sprite, and setting it to override `Not Walkable`, but it is not being cut from the mesh.

## Steps to reproduce
1. Create a tile grid with walkable areas
2. Create a new GameObject with a 
   * `Sprite Renderer`, scale the sprite to be big, several tiles large
   * `PolygonCollider2D`, give it a shape so the player can walk on some part of the sprite
   * `NavMeshModifier`, set to override "Not Walkable".
3. Create a new GameObject with a 
   * `NavMeshSurface2d`, have the "Default Area" be `Walkable` and set "Use Geometry" to `Physics Colliders`
4. Bake the nav mesh using the `NavMeshSurface2d`

### Expected results 
The `PolygonCollider2D` bounds should be cut from the baked NavMesh

### Actual results
Nothing is cut from the NavMesh.

## Workarounds
One workaround is to use several `Nav Mesh Obstacle`s to approximate the collision shape, but I'd really prefer to use the more flexible `Polygon Collider 2D` because of the complex shape and out of some concern for performance.

## Potential Bug Source
I think the issue arises because NavMeshPlus detects the `NavMeshModifier` is attached to a sprite and tries to use the sprite vertices before checking for any colliders on the GameObject.

# Thanks

Thanks again for the script, please let me know if you need any more information.

**Comment by h8man** [comment]
Hello,

Before bake select one of two geometry sources Mesh or Physics

Look for more details
https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#used-geometry

**Comment by mezz** [comment]
Thanks for the example in the demo project.
After comparing the projects and stepping through the debugger, I think I found the cause of the issue.

The issue in my setup was that my sprite was placed in the root of the scene and so it was not detected by the `NavMeshBUilder2d`. If I put my sprite as a child of my `Grid` GameObject, it is detected and the nav mesh is baked as expected. I am not sure if this is how the system is meant to work or not, I'd appreciate your feedback on how to organize the scene structure.

**Comment by h8man** [comment]
Hello,

Yeah, this statement missing in documentation. "Collect Objects" options are not supported, its always child.
Sorry for inconvenience, I will update documentation.

**Comment by mezz** [comment]
Thanks!
