### ISSUE TITLE
Navmesh holes when using changing "cell swizzle" & tilemap orientation

### ISSUE THREAD

**Issue by zxubian** [h8man/NavMeshPlus#35]
Steps to reproduce:

- add a Grid
- set swizzle to XZY
- Add 2 tilemaps to the grid
    - make one the ground, adding navmesh modifier and overriding the area to "walkable"
    - make the other one the walls, adding navmesh modifier and overriding the area to "unwalkable"
    - set both tilemaps' orientation to xz
 - add a NavmeshSurface2D to an empty object
 - set up the agent size etc
 - bake

Issues: 
- while the navmesh is correct for the indoor walls, there's a gap between the indoor area and the outdoor area, disallowing agents to enter/exit the building (see first image below)

![image](https://user-images.githubusercontent.com/8446683/104089620-b12be680-52b3-11eb-8a9d-57434013f7a9.png)

The issue does not appear when the swizzle & tilemap orientation settings are left at their defaults. (see image below)

![image](https://user-images.githubusercontent.com/8446683/104089644-dddffe00-52b3-11eb-9031-85f135ced8b9.png)

Specs:
  - Unity 2020.2.1f1
  - NavMeshPlus: latest (from Git)

**Comment by h8man** [comment]
Hello,

I have tried couple of scenes from https://github.com/h8man/RedHotSweetPepper and didn't find any artifacts when swizzle set to XZY and tilemap to xz.

Does `NavMsehSurface2d - Advanced - Default Area` set to Walkable?
