### ISSUE TITLE
Why does the Z axis change in demo

### ISSUE THREAD

**Issue by sherlock221** [h8man/NavMeshPlus#37]
Hi ~
I run demo and find that the z-axis is not 0. I don't know what the problem is

![image](https://user-images.githubusercontent.com/5842676/106556465-9ec36680-655a-11eb-8807-ec1a5b243ddc.png)

**Comment by h8man** [comment]
Hello @sherlock221 

The agent is moving on Z axis cause agent - Base Offset is set to 0.5
You can change offset to 0, it should help.

**Comment by sherlock221** [comment]
Thank you for your answer. 
I tried again, but I still can't
Z it's a fixed value 

![image](https://user-images.githubusercontent.com/5842676/106595134-15c62280-658e-11eb-98ea-528df04dbaa4.png)

**Comment by h8man** [comment]
@sherlock221, you right, the value oscillates on 0.0333..
You can disable agent position update `Agent.updatePosition = false` and sync position in update with `Agent.nextPosition`
This is Unity behavior and nothing todo with NavMeshPlus, its only bakes navmesh.

**Comment by sherlock221** [comment]
all right ,Thank you very much for your help
