### ISSUE TITLE
Small obstacle avoidance radius stops pathfinding

### ISSUE THREAD

**Issue by foldthirteen** [h8man/NavMeshPlus#39]
In an effort to try and stop agents bumping into each other and getting stuck, i've tried lowering the obstacle avoidance radius - but anything below 0.3 stops pathfinding from occuring.
My end goal is to get agents being able to use the same space for navigation - but feel like i've come unstuck trying to get this working.  To smaller avoidance radiance and the bottom seems to fall out on 2d pathfinding... 

l was wondering if this had something to do with where the agent sits vs. where the nav mesh is, and the agent is perhaps not considered 'on the navmesh' if he has too smaller radius...

**Comment by h8man** [comment]
Hello @foldthirteen 

NavMeshPlus doesn't make pathfinding, only helps to produce NavMeshSurface.
NavMeshSurface and Agent are standard Unity components, so there more chances to find answer on Navigation part of Unity's Forum. 

As for your question: avoidance radius should be greater than agents radius, if they are the same I believe they may not work as intended. But I don't have answer to your question, its only a assumption

**Comment by foldthirteen** [comment]
Hey, thanks very much for the answer and the insight about the agent radius.    
These are probably enough clues to help point me in the right direction, this morning I'd also looked at temp turning off collision avoidance on agents getting in each others space.

But yes, all things probably to do more with pathfinding and less with your tool.


Thanks very much for the asset, is supercool.
