### ISSUE TITLE
Inaccurate baking

### ISSUE THREAD

**Issue by gLenczuk** [h8man/NavMeshPlus#40]
Hey! I've setup your NavMeshPlus, but I have problem as you can see on screen:

![image](https://user-images.githubusercontent.com/53709984/107943228-af2d0580-6f8c-11eb-89c9-a91f92bfd77b.png)

Mesh is really inaccurate. I have 3 tilemaps. Ground, OnGround and Objects. Objects are marked as not walkable. I didn't make any extra steps. Object tilemap has tilemap collider with composite collider.

Could you help me? What can be reason?

**Comment by h8man** [comment]
Hello @gLenczuk 

What do you mean inaccurate? How desired NavMesh should look like?

NavMesh show were CENTER of agent can go, so it is around objects on equal distance that is equal to agent radius. Bigger the radius = further distance from objects
https://forum.unity.com/threads/2d-navmesh-pathfinding.503596/page-6#post-6829343 
![image](https://user-images.githubusercontent.com/44724892/107961372-7f8ef500-6fae-11eb-89b3-7e93dba99cd2.png)

**Comment by gLenczuk** [comment]
I mean, that mesh is too far from obstacles. My agents will be small and with that setup, player can hide near obstacle and agent never will get him.

And I have some enemies, that have to collide with player to deal damage, and thats the problem.

**Comment by h8man** [comment]
@gLenczuk 

Change Agent radius to match your need. Distance to object is equal to Agent radius

![image](https://user-images.githubusercontent.com/44724892/107962674-e660de00-6faf-11eb-8747-f2641f7018ba.png)
![image](https://user-images.githubusercontent.com/44724892/107962954-3cce1c80-6fb0-11eb-9efb-3028bd8ffea5.png)

**Comment by gLenczuk** [comment]
I've changed agent radius and it works. Thank you! I close this issue.
