### ISSUE TITLE
NavMeshAgent - Invisible Sprite

### ISSUE THREAD

**Issue by jlindy12** [h8man/NavMeshPlus#42]
Hello!

I am new to game development and am working on a top-down 2D adventure game in Unity. I am attempting to use NavMeshPlus for my enemy pathfinding, but I am running into an issue of disappearing sprites.

The issue arises when I add a NavMeshAgent component to my enemy game object. The sprite will be visible within the "Scene" view, but as soon as I move into the "Game" view the sprite disappears.

The NavMesh itself works well and seems to pick up on all of my collision tiles after baking, but I haven't been able to find any fixes for the disappearing sprites online. Hoping you'll be able to help. Thanks!

![image](https://user-images.githubusercontent.com/79230124/108275377-3ffa1180-7144-11eb-9688-039ef3587610.png)

![image](https://user-images.githubusercontent.com/79230124/108275464-64ee8480-7144-11eb-9920-5f23d5fb2d06.png)

**Comment by h8man** [comment]
Hello @jlindy12 

Hope it will resolve the issue

https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#nav-mesh-plus

Important note: When a "Nav Mesh Agent" starts to interact with your scene (e.g., when they start to move in-game) the system tends to rotate the GameObject upon which the component is placed. This can be undesirable (as in, your object may be rotate away from your plane of view and hence become invisible), so you should fix its rotation by adding something like the following to a new or existing script:

	void Start()	{
		var agent = GetComponent<NavMeshAgent>();
		agent.updateRotation = false;
		agent.updateUpAxis = false;
	}

**Comment by jlindy12** [comment]
Hey @h8man, thanks for the quick response!

I thought I had that taken care of but had it included within a parent script instead (whoops). 

That seemed to do the trick for the disappearing sprite, but now I can't get the agent to actually find a path around any of my non-walkable areas. Are there any known components, scripts, objects, etc. that would interfere with pathfinding?

![image](https://user-images.githubusercontent.com/79230124/108284726-c2d69880-7153-11eb-807c-057426ae7273.png)

**Comment by h8man** [comment]
@jlindy12 

Not sure, check console messages and try to debug these values NavMeshAgent.pathStatus, NavMeshAgent.hasPath, NavMeshAgent.path

**Comment by jlindy12** [comment]
@h8man 

I don't have any errors showing in the console. Do you know which script houses those values? Sorry, never had to debug before so not sure where to start.

**Comment by h8man** [comment]
@jlindy12 

In a script where you have something like this Agent.SetDestination(target.transform.position);
You can then `Add to watch` via context menu to inspect object at runtime.

**Comment by CiriousJoker** [comment]
I had the same issue, in my case this was the solution:

Set the initial transform position & rotation to 0/0/0 & 0/0/0, otherwise the entity spawns at 0/0/-1 & -90/0/0 (thus being invisible). 

This needs to be done in `Awake()`, `Start()` will **not** work.
