### ISSUE TITLE
Programmatic build nav mesh uses previous build

### ISSUE THREAD

**Issue by GitFlip** [h8man/NavMeshPlus#43]
Hey again @h8man!

Running into another issue and probably doing something wrong, but wanted to see if you've seen this scenario:

We've been randomly generating our tilemap and then programmatically calling the `NavMeshSurface2d.BuildNavMesh()` using a custom GUI Editor button on our component that generates the level and builds the NavMesh. We had some issues at first, but as you may recall in #41 we were able to resolve them.

Now that we're happy with our random level generation, we'd like to do it at the start of the scene when playing. Our level generation works and the `BuildNavMesh()` sort of works. It builds the nav mesh, but it doesn't use the same NavMesh data file, and for some reason though the NavMesh that is applied is the one that was last generated programmatically via our custom GUI Button.

I suppose the important thing to keep in mind is that whether or not you press the our GUI button to generate the level or start the scene to generate the level, the same exact code is being called.

Here are some screenshots - hoping you my have some suggestions on where to start investigating:

Pressing our Custom GUI Generate Level button works as intended:
![image](https://user-images.githubusercontent.com/735711/111105144-aea27300-8528-11eb-821a-ca3d1f8d3212.png)

After pressing Play a new level generates, but it using the previous generated NavMesh (notice the Nav Mesh Data is just called `NavMesh` now though):
![image](https://user-images.githubusercontent.com/735711/111104639-86664480-8527-11eb-94a1-f673f983536b.png)

After stopping the scene, our tilemap  will revert to the last level we had generated outside of play mode (this is normal) and of course it's Nav Mesh Data is back to `NavMesh-NavMesh`
![image](https://user-images.githubusercontent.com/735711/111105208-d98cc700-8528-11eb-8e06-1468171bac4d.png)

And the file `NavMesh-NavMesh` does actually exist:
![image](https://user-images.githubusercontent.com/735711/111105248-f0331e00-8528-11eb-9229-98f4a15d8f11.png)

**Comment by h8man** [comment]
Hello @GitFlip 

I believed its because of NavMeshData. NavMeshData is a "handle/object" to NavMesh native implementation inside Unity, and NavMeshSurfcace is only a wrapper. So `NavMeshSurface2d.BuildNavMesh()` creates new data, and you see it in the inspector.

I made this script
`class AutoBake: MonoBehaviour
    {
        public NavMeshSurface2d Surface2D;

        void LateUpdate()
        {
            Surface2D.BuildNavMesh();
        }
    }`
And I get what I believe correct result (shifted -1 on X)
![image](https://user-images.githubusercontent.com/44724892/111145443-eb09b980-8590-11eb-93df-e13a0a2818d9.png)

So I'm not sure what is happening in your scenario, but `Bake` button doesn't call `NavMeshSurface2d.BuildNavMesh()`.
Instead what `Bake` does is: 1st it manages resources (prefab/asset) and then create empty `NavMeshData` and fill in with new sources
`                oper.bakeData = InitializeBakeData(surf);
                oper.bakeOperation = surf.UpdateNavMesh(oper.bakeData);`

Try use `surface.UpdateNavMesh(surface.navMeshData);` maybe it will solve issue.

Please share your findings.

**Comment by GitFlip** [comment]
Hi @h8man 

Thanks for the reply. I tried using `surface.UpdateNavMesh(surface.navMeshData);` and while it did update the Nav Mesh Data be named `NavMesh-NavMesh`, it didn't fix anything.

I noticed though that you were calling `BuildNavMesh()` in your example component in the `LateUpdate()` method. We are calling it in the `Start()` method.

I moved it to the `LateUpdate()` and put a condition so it's not baking every update:

```C#
        private void LateUpdate()
        {
            if (bakeMesh)
            {
                Debug.Log("Baking Nav Mesh");

                navMesh.BuildNavMesh();

                bakeMesh = false;

                Debug.Log("Done Baking Nav Mesh");
            }
        }
```

And this did work! I was curious if it worked in the `Update()` method, but it doesn't. So is there a reason that it needs to be called in `LateUpate()`?

**Comment by h8man** [comment]
@GitFlip 

I put it into late update as I don't know the order of execution.
Maybe mesh bake was called before level got generated? Or something get updated later

**Comment by GitFlip** [comment]
> @GitFlip
> 
> I put it into late update as I don't know the order of execution.
> Maybe mesh bake was called before level got generated? Or something get updated later

We generate the whole level first at `Start()` and then do the bake, so everything should be generated already.

In you update your `AutoBake` component to do the `Surface2D.BuildNavMesh();` in `Start()` instead of in `LateUpdate()` does it still work for you?

**Comment by h8man** [comment]
No, it doesn't work in update or start, weird.

**Comment by h8man** [comment]
@GitFlip 

Just made runtime baking sample scene for experiments in RedHotSweetPapper.
Bake does work in update() or start() however.

Take a look and experiment for yourself

**Comment by GitFlip** [comment]
@h8man 

Thanks for putting that scene together. I played around with it and it does seem to be working. I decided to then edit it  a bit to see if I can make it even more like my scene:  Use Physics Colliders, add a tile to the tilemap at `Start()`, and then bake.

I essentially just updated your `RuntimeBake` to this:

```C#
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.Tilemaps;

namespace Assets.Scripts
{
    class RuntimeBake: MonoBehaviour
    {
        public NavMeshSurface2d Surface2D;
        public Tilemap wallTilemap;
        public Tile tile;

        public int TilePosX = -8;
        public int TilePosY = 5;

        void Start()
        {
            wallTilemap.SetTile(new Vector3Int(TilePosX, TilePosY, 0), tile);

            Physics2D.SyncTransforms();

            Surface2D.BuildNavMesh();
        }
    }
}
```

I then disabled all of your Wall Tilemaps and created my own adding of course a Tilemap Collider 2D component to it. I then did a bake in the editor to reset the nav mesh and then before pressing play, I also added one wall tile to use as a base to ensure it works for a tile added before. Sure enough when I enabled the component in the scene, it worked correctly:

https://i.gyazo.com/9f331fbefc4ab5c4b54279b233699c3b.gif

Then, I copied that script over to my application, and did the exact same thing, but for me, the tile that gets added at `Start()` does not get cut out of the navmesh, the tile that was there beforehand does though:

https://i.gyazo.com/9dcf7241ea5014a22b9122b0f96ec86b.gif

As far as I can tell both of our tilemaps are set up the same and so are the NavMeshSurface2d. One thing that is different is I'm using the Isometric tilemap, but I don't think that would cause the problem. I'm not quite sure how to go about debugging the `BuildNavMesh()` though, so any suggestions are welcomed!

Thanks!

**Comment by GitFlip** [comment]
AHH wait!! I was rewatching that first gif, I never set the Use Geometry to Physics Collider in your project. When I do set it to that, I'm able to reproduce the issue in your scene:

https://gyazo.com/6eb49551570b59e4e6873637c4ef9897.gif

So it has something to do with the Physics Collider for the geometry, even if I have the `Physics2D.SyncTransforms();` being called before the `BuildNavMesh()` 🤔 

Let me know if you need help reproducing the issue (I can push on a branch if you want), or how I can help further.

Thanks!

**Comment by GitFlip** [comment]
Hey @h8man did you see my comments above? Were you able to reproduce the issue then? Let me know if you need me to push a branch with the issue.

Thank you!

**Comment by h8man** [comment]
Hello, @GitFlip 

I have seen the message, I just didn't have time to open unity and look what is happening. It pretty straight forward to reproduce. I will come back to this shortly

**Comment by h8man** [comment]
@GitFlip 

Hi,

1) I selected physics sources
2) add box collider
3) add navmeshmodifier to collider
4) add tilemap collider

And I got the same navmesh as it was before modification. Than I recall that nothing is updated till fixed update. Physics not only updated only in fixed update, fixed update is running in different time period. So its is not possible to generate physics in Awake/Start.

So script should wait till first Fixed Update and than call bake.

```
        void Update()
        {
            Surface2D.BuildNavMesh();
            enabled = false;
        }
``` 

![image](https://user-images.githubusercontent.com/44724892/112643226-cb09ae00-8e4c-11eb-989b-391e4e408003.png)

**Comment by GitFlip** [comment]
> Hello, @GitFlip
> 
> I have seen the message, I just didn't have time to open unity and look what is happening. It pretty straight forward to reproduce. I will come back to this shortly

@h8man No worries, thanks for checking. I just wanted to make sure you didn't need any assistance.

Your second reply makes sense to me. I guess maybe this issue can be closed then. Perhaps it makes sense to update the wiki again with this information? Also, I'm wondering if NavMeshPlus can log a warning if you call `Bake()` before the first fixed update is called 🤔

**Comment by h8man** [comment]
@GitFlip 

Nice idea about warning. Also I will update wiki.

**Comment by rhys-vdw** [comment]
> Than I recall that nothing is updated till fixed update. Physics not only updated only in fixed update, fixed update is running in different time period. So its is not possible to generate physics in Awake/Start.

It should be possible to do raycasting and other physics based operations at any time, all that happens in `FixedUpdate` is `Physics2D.Simulate` (assuming you have `Physics2D.autoSimulate` enabled).

**Comment by h8man** [comment]
warning added
