### ISSUE TITLE
Generating navmesh at runtime

### ISSUE THREAD

**Issue by rhys-vdw** [h8man/NavMeshPlus#44]
Is it currently possible to generate a navmesh at runtime, and if not, is this because it would be difficult to do?

Also, unrelated, how can I set the size of the scanned area? My game has no tilemap and there seems to be no way to directly set a grid's width and height. I've resorted to adding a grid and tilemap with corner tiles and its renderer disabled.

Thanks!

**Comment by h8man** [comment]
Hello @rhys-vdw 

Yes, it is possible to bake navmesh runtime or even update every frame. It is not explicitly referred in wiki yet.

But you can look at these samples:
https://github.com/Unity-Technologies/NavMeshComponents/tree/master/Assets/Examples/Scenes
https://github.com/h8man/RedHotSweetPepper/tree/master/Assets/Scenes

Also this information somewhat in wiki already, but you may want to read it in full details
https://github.com/h8man/NavMeshPlus/issues/41
https://github.com/h8man/NavMeshPlus/issues/43

**Comment by rhys-vdw** [comment]
> I will update about world bounds latter as I'm not sure about current implementation

Thanks @h8man, this is a great start! I've worked out how to define the world bounds. I simply provide one child collider that is the exact shape of the world (in my case a circle) and leave the "override" button unchecked. This way the bounds will be expanded to cover the object [here](https://github.com/h8man/NavMeshPlus/blob/d4e1f78439ab44dd98c07e8bdb791e9375e85ac1/NavMeshComponents/Scripts/NavMeshSurface2d.cs#L419).

**Comment by h8man** [comment]
Hello @rhys-vdw 

I checked current implementation and `SampleSceneNoTileMap` sample scene that I made earlier, and found that there is no way to define world bound except to introduce world bound `GameObject` with `navmeshmodifier`. That exactly as in your sample.

I see that `navmeshsurcafe` has world bound definition but only for `Volumes`  and only in square bounds. So I believe you need explicit world bounds by design.

**Comment by rhys-vdw** [comment]
Hey thanks @h8man. So I think there's room for this to be mentioned in the wiki:

> NavMeshSurface2d can bake objects that are not a part of Tilemap, or even if there is no Tilemap.
[https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#non-tiled]

**Comment by h8man** [comment]
Added - Important note: Currently there is no way to define world bound except to introduce explicit world bound GameObject with NavMeshModifier

Wiki is open for edits
