### ISSUE TITLE
NavMeshSurface2D editor not rotated correctly

### ISSUE THREAD

**Issue by rhys-vdw** [h8man/NavMeshPlus#45]
I lost a few hours when I accidentally unrotated my NavMeshSurface2D:

> Name your new empty GameObject, name it "NavMesh", and rotate it -90, 0, 0.
https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#nav-mesh-plus

Some ideas for improving this:
- Show a warning in inspector when the object is incorrectly rotated.
- Provide a prefab object for the nav mesh surface that has an additional script that forces it to be rotated correctly.
- Ignore object rotation when generating a surface (if possible/appropriate)

I'd be open to contributing this change.

**Comment by rhys-vdw** [comment]
> Ignore object rotation when generating a surface (if possible/appropriate)

This could probably be achieved [here](https://github.com/h8man/NavMeshPlus/blob/master/NavMeshComponents/Scripts/NavMeshSurface2d.cs#L189-L190):

```cs
var position = transform.position;
position.z = 0;
var data = NavMeshBuilder.BuildNavMeshData(
    GetBuildSettings(),
    sources,
    sourcesBounds,
    position,
    Quaternion.Euler(-90, 0,0)
);
```

Do you think there are any cases where using a different z position or rotation is desirable?

**Comment by h8man** [comment]
@rhys-vdw 

Z is used for isometric tilemaps to introduce depth, it may happen that some one would have 2 meshes on top of each other.
There is a dedicated button to rotate your mesh.

The nest solution is to add warning

**Comment by h8man** [comment]
@rhys-vdw 

add - Show a warning in inspector when the object is incorrectly rotated.
