### ISSUE TITLE
`GetRoot` fails with `NullReferenceException` when scene has no Grid

### ISSUE THREAD

**Issue by rhys-vdw** [h8man/NavMeshPlus#46]
https://github.com/h8man/NavMeshPlus/blob/d4e1f78439ab44dd98c07e8bdb791e9375e85ac1/NavMeshComponents/Scripts/NavMeshBuilder2d.cs#L72

This line throws when using a NavSurface2d set to `CollectObjects2d.All` without a `Grid` object. A `Grid` is not required when using colliders. It seems as though `CollectOptions.Children` is the only option compatible.

Also, if you _do_ add a grid at the root of colliders, it complains "NullReferenceException: Add at least one tilemap", rather than simply scanning its children for colliders.

I think it should be pretty straight forward to either 1. scan the whole scene for geometry, or 2. fix these errors by preventing invalid configurations in the inspector.

**Comment by rhys-vdw** [comment]
This is also the cause of #29. Would you be open to a PR?

**Comment by h8man** [comment]
@rhys-vdw 

What you say sounds reasonable, but also it will encourage using `All` for all cases, and its terrible for runtime.
Also it will not work with current implementation, as it will scan child object twice (if we have nested objects).

I believe there should be only one option to exist - `Children`. Unity encourage bad design by their half working git repos, and this repo inherits that.

But yeah. Its open for PR

From Wiki:
_Important note: NavMeshSurface2d should be a parent for all colliders if this option enabled. See NON-TILED below...
... place all GameObjects with NavMeshModifier that define your layout under object with NavMeshSurface2d, and select appropriate option Collect Objects - Children_

**Comment by rhys-vdw** [comment]
I agree that it should be the only option. Would you be open to such a PR? Then you can remove the note in the guide.

**Comment by h8man** [comment]
I'd like this approach for now.

> 2. fix these errors by preventing invalid configurations in the inspector.
