### ISSUE TITLE
Proposal: BuildNavMeshAsync

### ISSUE THREAD

**Issue by rhys-vdw** [h8man/NavMeshPlus#47]
I need to build a navmesh asyncronously at runtime. Although `NavMeshBuilder` exposes no `BuildNavMeshDataAsync` it's quite trivial to implement via [this method](https://github.com/Unity-Technologies/NavMeshComponents/issues/97#issuecomment-528692289).

I would like to add `AsyncOperation NavMeshSurface2d.BuildNavMeshAsync()` for this purpose.

Would you be interested in a PR adding this feature?

**Comment by h8man** [comment]
Yes.
