### ISSUE TITLE
Disable source count debug log

### ISSUE THREAD

**Issue by rhys-vdw** [h8man/NavMeshPlus#48]
https://github.com/h8man/NavMeshPlus/blob/86ceea0dfe7bcd8db2a486bd68c4c095ae4299e0/NavMeshComponents/Scripts/NavMeshBuilder2d.cs#L144

This was useful, but I think there should be an option to disable trace logs as they're messing up my console. Would accept a PR?

**Comment by h8man** [comment]
There is a commit https://github.com/codxr02/NavMeshPlus/commit/11c246c053279e0d057abea6d0bb1bbc2df195cf
I will use it.

**Comment by rhys-vdw** [comment]
Thanks, that's perfect.

**Comment by h8man** [comment]
Hello @rhys-vdw 
Done with modified code form @codxr02 commit
