### ISSUE TITLE
Error after updating to Unity 2018.3.0

### ISSUE THREAD

**Issue by seelang2** [h8man/NavMeshPlus#5]
I just upgraded my Unity install from 2018.2.16 to 2018.3.0 this morning and on opening my project I received the following warnings and error:

Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshSurface.cs(371,30): warning CS0618: 'PrefabUtility.GetPrefabType(Object)' is obsolete: 'Use GetPrefabAssetType and GetPrefabInstanceStatus to get the full picture about Prefab types.'

Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshSurface.cs(372,31): warning CS0618: 'PrefabType' is obsolete: 'PrefabType no longer tells everything about Prefab instance.'

Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshSurface2d.cs(465,30): warning CS0618: 'PrefabUtility.GetPrefabType(Object)' is obsolete: 'Use GetPrefabAssetType and GetPrefabInstanceStatus to get the full picture about Prefab types.'

Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshSurface2d.cs(466,31): warning CS0618: 'PrefabType' is obsolete: 'PrefabType no longer tells everything about Prefab instance.'

Assets/NavMeshPlus/NavMeshComponents/Scripts/NavMeshSurface2d.cs(470,26): error CS0039: Cannot convert type 'UnityEngine.AI.NavMeshSurface2d' to 'UnityEngine.AI.NavMeshSurface' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion

**Comment by h8man** [comment]
thanks, issue resolved. I appreciate your feedback
