### ISSUE TITLE
Why is a 1x1 tile not detected as walkable?

### ISSUE THREAD

**Issue by RedLime** [h8man/NavMeshPlus#51]
![image](https://user-images.githubusercontent.com/25276450/113671892-ee0c4b80-96f1-11eb-843f-9adf5c3176c8.png)
As in this picture, 1x1 tiles that are closed on all sides are not detected.

![image](https://user-images.githubusercontent.com/25276450/113671938-fb293a80-96f1-11eb-959a-a56249f400d3.png)
I tried changing the radius, but the result is the same. Why is this 1x1 tile not detected as walkable?

**Comment by h8man** [comment]
Hello @RedLime 

Reduce tile size in NavMeshSurface2d, cause Unity does not sees it as significant.
![image](https://user-images.githubusercontent.com/44724892/113683273-af17cf00-96cc-11eb-8fb2-010d52466e15.png)

**Comment by RedLime** [comment]
> Hello @RedLime 
> 
> Reduce tile size in NavMeshSurface2d, cause Unity does not sees it as significant.
> ![image](https://user-images.githubusercontent.com/44724892/113683273-af17cf00-96cc-11eb-8fb2-010d52466e15.png)
> 

The same symptoms appear. 
Do I need to adjust the Voxel size?

Apart from the question, what is the association between Voxel Size and Tile Size?

**Comment by h8man** [comment]
@RedLime Voxel Size and Tile Size is a part of  Unity API. See documentation about recommended values  https://docs.unity3d.com/Manual/class-NavMeshSurface.html

**Comment by RedLime** [comment]
> @RedLime Voxel Size and Tile Size is a part of  Unity API. See documentation about recommended values  https://docs.unity3d.com/Manual/class-NavMeshSurface.html 

I was able to detect 1x1 tiles by adjusting Voxel Size and Tile Size, but the performance of the Bake process is very low.

Is this Navmesh's own problem? Should I look for another pathfinding solution?

sorry for many questions :<

**Comment by h8man** [comment]
@RedLime - NavMeshSurface uses Unity API. It just a manager on top of NavMeshBuider, so there nothing I can do with Bake performance. You can try to play with parameters or use 3rd party pathfinding. I didn't try any other solution for pathfinding, but seems "A* Pathfinding Project - Arongranberg" is the most popular.
