### ISSUE TITLE
Why is my navmesh created like this?

### ISSUE THREAD

**Issue by svnstrvck** [h8man/NavMeshPlus#56]
![wtf2](https://user-images.githubusercontent.com/87519179/125911445-fd60865e-2d9c-4be0-b842-f02dae27282e.PNG)

There's like.. this padding around everything and the area's don't connect to each other,

blue are walls

using Unity 2021.1.15f1

**Comment by h8man** [comment]
Hello @svnstrvck ,

Navmesh draws where the **center** of the Agent can reach, not his edge.

Reduce Agent's radius to get navmesh in corridors. Also in "Advanced Options" you can change precision and tile size of navmesh. 

![image](https://user-images.githubusercontent.com/44724892/125931978-9c19017d-0b9b-4384-892b-e61e2a5e0be2.png)

**Comment by svnstrvck** [comment]
> Navmesh draws where the **center** of the Agent can reach, not his edge.

Okay, yeah that makes sense.

> Reduce Agent's radius to get navmesh in corridors. Also in "Advanced Options" you can change precision and tile size of navmesh.

Changing agent's radius doesn't change the navmesh.. and tilesize doesn't do much either.

**Comment by h8man** [comment]
It should change size of new navmesh. Check agent type and radius before bake. NavMesh is not updated automatically.
![image](https://user-images.githubusercontent.com/44724892/125952651-f856dfad-bf12-4fd2-85f8-63f1c901b6da.png)

**Comment by svnstrvck** [comment]
> It should change size of new navmesh. Check agent type and radius before bake. NavMesh is not updated automatically.

Thanks, changing the Radius within the navigation pane worked.
