### ISSUE TITLE
Sprites do not render properly

### ISSUE THREAD

**Issue by justbake-bit** [h8man/NavMeshPlus#58]
When I add a Nav mesh agent component to my sprite and press play, the sprite becomes perpendicular to the nav mesh surface. How do I fix this? is it a feature that I have to change?

**Comment by h8man** [comment]
Hello

It is expected. You need to disable update axis:
https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#nav-mesh-basics

	void Start()	{
		var agent = GetComponent<NavMeshAgent>();
		agent.updateRotation = false;
		agent.updateUpAxis = false;
	}

**Comment by h8man** [comment]
Resolved
