### ISSUE TITLE
Is it possible to make the Mesh shape be built as close as possible to the Tilemap?

### ISSUE THREAD

**Issue by MaykerStudio** [h8man/NavMeshPlus#59]
If yes, can someone guide me to do it?

I'm currently working on a Pathfinding system for platformer 2D and I need the mesh to be carved based on the Grid, meaning that I need those gaps to be filled as shown in the image below. I tried the "Use Mesh Prefab" with a small quad but it doesn't work as I need.

![image](https://user-images.githubusercontent.com/54370952/141536146-433e082b-7121-491b-a7bf-b10457951660.png)

Best regards.

**Comment by h8man** [comment]
Hello @MaykerStudio 

I'm not sure that NevMesh pathfinding is suited for platformers, unless you have some intended use.

Back to your issue. NavMesh shows where the CENTER of an agent can reach. If agent radius 0.5 units, NavMesh will have a gap of 0.5, as center of agent cannot be closer than that value, but the edge of agent can "leave" NavMesh area.

Reduce Agent radius and bake again.

**Comment by MaykerStudio** [comment]
Oh, thanks a lot!
