### ISSUE TITLE
Not working on TilemapCollider2D

### ISSUE THREAD

**Issue by superfrantv** [h8man/NavMeshPlus#6]
Hello, iam using this and there is no "Grid" Option (Collect Objects) like the Tutorial say.
Iam using a Tilemap2DCollider and it not working. I followed the tutorial

**Comment by h8man** [comment]
Hi, tutorial is outdated on one revision. You don't need Grid option, as well as TilemapCollider. Correct steps to do bake is listed in README
You need NavMeshModifier component on Tilemap that you want to include into bake. Please follow to Unity forum for further discussion.

**Comment by h8man** [comment]
Tutorial Updated
