### ISSUE TITLE
Can this be used without tilemaps? using sprites and colliders.

### ISSUE THREAD

**Issue by hesamzkr** [h8man/NavMeshPlus#63]
Hello, Is it possible to use this package by using sprites and colliders to bake the Navmesh?
for example using open sprite shapes and 2D edge colliders. If it is could you tell me how, I'm not sure how.
Thank you.

**Comment by h8man** [comment]
Hello @hesamzkr 

Yes, you can use it without tilemap, here is wiki https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#non-tiled
And also there scene in demo https://github.com/h8man/RedHotSweetPepper

But its only sprites or colliders, not both.
