### ISSUE TITLE
Using the Transform of a Prefab within an Agent script doesnt return anything.

### ISSUE THREAD

**Issue by Noxfr69** [h8man/NavMeshPlus#64]
Hi, absolutly love the work, amazing tool really.

I encountered an issue, my player is inside a Prefab and it links to other script without any issues, but when I link it with an Agent script the player.transform.position doesn't get transmited and stay at (0,0,0).
Unpacking my player and using a non prefab instance of it works so the problem really comes from the prefab.

Maybe it has to do with the 4 problems that are found in the code : 
	'prefabAssetPath has been deprecated. Use assetPath instead.' [NavMeshComponentsEditor]"

I tried replacing prefabAssetPath by assetPath, but it didn't change anything.
Any idea on how to fix this ?

Thank you so much again for the amazing work !

**Comment by h8man** [comment]
Hello, @Noxfr69

Thank you for a feed back. I will try to address warnings you are getting in console in a few days.
 
Can you share a print screen with the issue you are describing? Cause I'm not sure I'm quite understand what do you mean: player inside a Prefab not acting as expected.

Does you prefab essentially is a complex scene with a nav mesh and an agent inside?

**Comment by Noxfr69** [comment]
So my ennemy prefab has the nav agent and the script to make it move towards the player. To get the refference of the player position I use a public transform or public gameobject (tried differents options of getting the refference) but if my Player is also a prefab like this :
![prfab](https://user-images.githubusercontent.com/99217986/152882600-1e286e0e-98af-42a8-95ca-8de2eea0362e.png)

The target that is just a reference to the Player gameobject transfrom position dosent update and always stay (0,0,0)
But if I do it like this and take my Player out of the prefab it works just fine.

![Capture d’écran 2022-02-07 232429](https://user-images.githubusercontent.com/99217986/152882597-cb6f4cf0-69a5-46a7-8e18-cf875b54f29e.png)

**Comment by Noxfr69** [comment]
Well as often the problem was my understanding of unity haha, of course prefabs can't hold scene variable. And if they hold other prefabs it's not the one present in the scene it's just the general prefab. 

Using static variable to feed my prefab fixed the problem.

**Comment by h8man** [comment]
Great!

Anyway. Don't close this issue till I fix warnings.
