### ISSUE TITLE
Clear surface at runtime

### ISSUE THREAD

**Issue by yiliansource** [h8man/NavMeshPlus#66]
Hi,

I wasn't able to find anything in the PDF regarding this, but is it possible to clear the data of a `NavMeshSurface2d` at runtime, as opposed to building at runtime? The reason is that I have instances where I'm generating new levels at runtime, and don't want stale navigation data hanging around during this.

I tried
```cs
surface2d.RemoveData();
```
but that doesn't really seem to clear the data.

**Comment by h8man** [comment]
Hello @yiliansource 

From source code I see that clear button has next calls:
`if (GUILayout.Button("Clear"))
 {
     NavMeshAssetManager2d.instance.ClearSurfaces(targets);
     SceneView.RepaintAll();
 }`

In subsequence it's calling
`navSurface.RemoveData();`
and other clean up code. 

In a deeper dive it's calling https://docs.unity3d.com/ScriptReference/AI.NavMeshDataInstance.html
_Remove | Removes this instance from the NavMesh system._

So you need a reference NavMeshDataInstance to remove it from NavMesh system. And maybe the reference is overwritten or cleared before `Remove()` call. That's all I found for now. Hope I will have more info later.

**Comment by h8man** [comment]
@yiliansource 

I've pushed ClearNavMesh component to RedHotsweetPepper that clears nav mesh on "win" condition.
Open SampleSceneRuntime and select NavMesh object and press play, when game is over navmesh will disappear that shows that `surface2d.RemoveData();` does work.
