### ISSUE TITLE
How to change Mesh padding?

### ISSUE THREAD

**Issue by Tom-lister** [h8man/NavMeshPlus#67]
![PaddedMesh](https://user-images.githubusercontent.com/92087395/155898075-2019bdaa-b289-4b9d-b5ea-2f1dbce56a59.jpg)

Hello, I was wondering how to change the 'padding' of the generated mesh. As the image shows, tiles marked as Not Walkable are given a very wide birth by the algorithm, which results in blunt edges and, as a result, clunky agent movement. Is there a way to adjust how closely to obstacles the mesh is generated?

**Comment by Tom-lister** [comment]
Or, I suppose, a way to make the edges more rounded in general.

**Comment by h8man** [comment]
https://github.com/h8man/NavMeshPlus/issues/59
https://github.com/h8man/NavMeshPlus/issues/56
https://github.com/h8man/NavMeshPlus/issues/40

To "round" edges change advanced bake settings as https://docs.unity3d.com/Manual/class-NavMeshSurface.html
For smooth cornering adjust navmesh agent https://docs.unity3d.com/ScriptReference/AI.NavMeshAgent.html
Also there is static methods https://docs.unity3d.com/ScriptReference/AI.NavMesh.html
