### ISSUE TITLE
Type or namespace name 'NavMeshSurface2d' could not be found

### ISSUE THREAD

**Issue by CaptJazz1** [h8man/NavMeshPlus#68]
Hi,
As far as I can tell the 2D navmesh is still working, however as of a week or two ago, when I attach visual studio to unity for debugging, I get the following build error:
"CS0246 The type or namespace name 'NavMeshSurface2d' could not be found (are you missing a using directive or an assembly reference?)
Project: NavMeshComponentsEditor
File: NavMeshSurfaceEditor2d.cs

Any tips?

**Comment by h8man** [comment]
Hello, @CaptJazz1 

As you may know, components are distributed without *.proj file, its generated by Unity.
So just remove generated NavMesh *.proj files and unity will create new one.

Hope it helps

**Comment by Tom-lister** [comment]
Hi, @h8man 

I am having the same problem but don't quite understand your solution. Where are these .proj files located? I found and removed "NavMeshComponents.csproj" and "NavMeshComponentsEditor.csproj", but this made no difference and Unity did not restore them.

(I am getting this error when attempting to define a variable "public NavMeshSurface2d Surface2D;" for the purpose of updating the mesh during runtime)

Thanks for your help so far!

**Comment by h8man** [comment]
Hello @Tom-lister,

I cannot reproduce the issue (as there is no steps), so I'm just sharing my thoughts that it can be bad project files.

how did you install NavMeshPlus? as package in Packages/manifest.json?

**Comment by Tom-lister** [comment]
Hi @h8man,

Thanks for your reply, I'm still very new to Unity so may have made a basic mistake.

I put all the repository files into MyProject/Packages/com.h8man.2d.navmeshplus

They show up in my project like this:

![image](https://user-images.githubusercontent.com/92087395/162293670-1a742ef0-cc76-43c9-8dbc-91e80c271d0a.png)

This is my code:

![image](https://user-images.githubusercontent.com/92087395/162293918-3cc0946a-ad1b-4cd7-a16f-4b908d87a5c0.png)

And the full error message is:

Assets\Scripts\MeshController.cs(7,12): error CS0246: The type or namespace name 'NavMeshSurface2d' could not be found (are you missing a using directive or an assembly reference?)

I did initially put the repository files in the Assets folder, but realised my mistake following your reply and corrected the error.

**Comment by h8man** [comment]
I'm not sure that you need to put it manually and add to manifest.json in the same time.

Lets me test this, and I will be back.

**Comment by Tom-lister** [comment]
Thank you! I wasn't aware that using `UnityEnging.AI;` was required - maybe it's obvious to experienced developers but I couldn't see it anywhere in the "HOW TO" document.

Line 7 is now accepted, but I'm also getting the error "The name 'surface' does not exist in the current context" for line 11. Is there another additional statement I need to include?

**Comment by h8man** [comment]
Put `Surface2D.UpdateNavMesh(Surface2D.navMeshData)`
