### ISSUE TITLE
Adding a box collider.

### ISSUE THREAD

**Issue by seanpen00** [h8man/NavMeshPlus#69]
When I add a box collider (or any other type of colliders) the NavMeshAgent stops being able to move. I followed this tutorial: 
https://www.youtube.com/watch?v=W-NIYi1t16Q

Could anyone help me out? Thank you!

**Comment by h8man** [comment]
Hello @seanpen00 

Please add timecode or share print screen of scene setup. Its hard to guess what is going on,
Also there is wiki page with tutorial https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#nav-mesh-basics
And demo project https://github.com/h8man/RedHotSweetPepper

**Comment by h8man** [comment]
no reply
