### ISSUE TITLE
No support for Box Collider 2D? 

### ISSUE THREAD

**Issue by NicholasOwenJones** [h8man/NavMeshPlus#71]
I tried using a Box Collider 2D with a NavMeshModifer and it didn't seem to recognise it as a non-walkable area. I can get it to bake correctly with a Box Collider and Physics Colliders, but I would have thought if this project is aimed at working with 2D it would include Box Collider 2D as an acceptable collider. Might be something to add in for the future?

It also doesn't appear to use the Sprite Renderer on the Render Meshes option, also might be useful to add in for 2D projects.

Great work so far! Keep it up!

**Comment by h8man** [comment]
@NicholasOwenJones 

Yes, navmeshsurface2d works with colliders, Box Collider 2D also.
Please check wiki and demo https://github.com/h8man/RedHotSweetPepper

**Comment by NicholasOwenJones** [comment]
Hmmm, strange. I'll have another look at it. I could get it working with Box Colliders, but as soon as I swapped it out for a Box Collider 2D it would stop baking the nav mesh correctly. Maybe I missed something, I'll have another try. Thanks for the fast response.

**Comment by h8man** [comment]
Form wiki:

Physics Colliders, this option allows navmesh to build surface form 2D colliders polygons. To do that place all 2D colliders with NavMeshModifier added into navmesh GameObject as child, change Use Geometry option from Render Meshes to Physics Colliders and hit bake.

Important note: NavMeshSurface2d should be a parent for all colliders if this option enabled. See NON-TILED below

**Comment by h8man** [comment]
Now collider2d is collected from all sources as well. I'm closing issue.

**Comment by murilobast** [comment]
Doesn't seem to be working with `CollectSources2d` it simply ignores any Mesh/Circle/Box Collider 2D. Is there anything else I should do to use my MeshCollider2D as a source?

**Comment by h8man** [comment]
Check demo for physics based NavMesh https://github.com/h8man/RedHotSweetPepper

**Comment by murilobast** [comment]
I managed to make it work after adding a `NavigationModifier` to one of my tilemaps. Even though I had a large `SpriteRenderer` (80x80 units) with a `NavigationModifier`.
