### ISSUE TITLE
Agent moves in the z-direction?

### ISSUE THREAD

**Issue by eduardmirzoyan** [h8man/NavMeshPlus#72]
For some reason, the nav agent has it's transform at a very small negative z value. This causes the agent to not be viewed in the camera. Does anyone else have issues with the agent getting a random z-direction displacement?

**Comment by h8man** [comment]
@eduardmirzoyan Hello,

Yes, some 0.0xxxxxxx are always there. You can offset z value with Agent - Base Offset property

*NavMesh agent in a part of Unity NavMesh.AI
