### ISSUE TITLE
Is there a way to override/mask the area if I put a sprite over a tilemap?

### ISSUE THREAD

**Issue by ndrwln** [h8man/NavMeshPlus#74]
Lets say I have various tilemaps showing terrain etc, and I put a road sprite with a collider. I try baking it, but although the area is set to a different type than walkable, the navmesh still isnt changed. Is there a way to layer these 2d navmeshes so that a sprite on top of a tilemap takes precedence?

tldr I want to paint a road on top of the walkable tilemap, and I want the navmesh agent to prioritize using the road.

**Comment by ndrwln** [comment]
Nvm, I found out the problem was because I was baking it in the navigation tab instead of going directly to the navmesh and baking.

**Comment by h8man** [comment]
https://github.com/h8man/RedHotSweetPepper/blob/master/Assets/Scenes/SampleSceneDiagonals.unity

You can use two tilemaps, or use timemap and sprites./
