### ISSUE TITLE
Nav Mesh Basics Intro not working

### ISSUE THREAD

**Issue by julesx** [h8man/NavMeshPlus#75]
I can't seem to get even the simplest setup to work in an empty 2D scene

NavMesh in Inspector
![image](https://user-images.githubusercontent.com/3010047/168723293-f6b946cf-e0d4-4061-8ac4-9315bae3e4a2.png)

GameFloor in Inspector
![image](https://user-images.githubusercontent.com/3010047/168723337-47791601-d213-4be4-8221-af4ef987a5cc.png)

When I Bake, no nav mesh appears to be generated.

**Comment by h8man** [comment]
Hello @julesx 

I made simple setup. And its seems to work. But your icons are sligtly different. Are you using NavMeshSurfaceComponents and NavMeshPlus together? I also need to check Unity 2022, so I will update my answear.
![image](https://user-images.githubusercontent.com/44724892/168752658-56e08308-f4e4-4e7d-804f-dcd7c5c0fd24.png)

**Comment by h8man** [comment]
Yep,

Your Icons are suspicious. I created project and added NavMeshPlus form github - it does work. Icons you have are from other components, so asume you have NavMeshSurfaceComponents installed - remove it.

**Comment by julesx** [comment]
oh man it works!! thanks so much
