### ISSUE TITLE
How would I prevent diagonal movement ?

### ISSUE THREAD

**Issue by LelouBil** [h8man/NavMeshPlus#78]
Hello, 
Do you have advice on how I could prevent diagonal movement of the agent ?

**Comment by h8man** [comment]
Hello @LelouBil 

Unfortunately unity doesn't provide you with Agent "overrides". So for such custom pathfinding you need to write your own agent. Its somewhat 40-100 hours of work, greatly depend on what you need.

**Comment by h8man** [comment]
Also you can check this thread https://github.com/h8man/NavMeshPlus/issues/70, I have no idea how custom movement was implemented.
