### ISSUE TITLE
About multiple navmeshagents?

### ISSUE THREAD

**Issue by sherlock221** [h8man/NavMeshPlus#79]
Thank you for your amazing component, I have been used for a long time.
Recently, I have a question about multiple navmeshagents. How can I handle the NavMeshSuface2d  , when  the radius  of each navmeshagents  is different. 
Is it need to use multiple  NavMeshSuface2ds? 
![image](https://user-images.githubusercontent.com/5842676/174566831-44e0224d-0153-46f5-884c-59498ee98686.png)

**Comment by h8man** [comment]
Hello @sherlock221 

Yes, you should use 1 surface per agent. That is by Unity's design.
