### ISSUE TITLE
Can't compile my project due to "NevMeshExtension requires NavMeshSurface component"

### ISSUE THREAD

**Issue by wmeints** [h8man/NavMeshPlus#83]
I've added this package to my project and it works fine inside the editor. But when I try to build and run my project, the build fails with the error "NevMeshExtension requires NavMeshSurface component". Search for this in the code, leads me to the following spot:

https://github.com/h8man/NavMeshPlus/blob/040ac9035ed336793c1cac844a01017c16873454/NavMeshComponents/Scripts/NavMeshExtension.cs#L47

I modified the code to remove the error log, and my project compiles fine. The game also works fine.

I'm not sure what's going on here. So I hope you can enlighten me.

**Comment by h8man** [comment]
Hello @wmeints 

I will check builds with navmesh to confirm this defect.

**Comment by h8man** [comment]
I checked RedHotSweetPapper build and reviewed source code. And found no issues.
The snippet you provided placed intentionally to warn you that there is no NavMeshSurface for NevMeshExtension.

I will change message type to Warning.
