### ISSUE TITLE
Not walkable areas are too big

### ISSUE THREAD

**Issue by Louis-Soltys** [h8man/NavMeshPlus#84]
Hi, I'm trying to generate a nevmesh with multiple tilemaps. I set the tilemap who contains my Tilemap Collider 2D as a "not walkable area" but when I bake the navmesh the range around not walkable tiles is way too big and I don't know how to reduce this range.
There is an example: 
![image](https://user-images.githubusercontent.com/61182965/183250225-3bda3988-6c82-4785-a6c3-2d753a2f2094.png)

Can someone help me ?

Thanks ! (And I'm sorry for my english) :)

**Comment by h8man** [comment]
@Louis-Soltys select your your agent and reduce its radius. Agents are in Navigation panel (Unity Window)

Q: How to change NavMesh padding?
A: Navmesh draws where the center of the Agent can reach, not his edge. Reduce Agent's radius to get navmesh closer to the edge. Bake again to see results.
