### ISSUE TITLE
How to create non-square navmeshagent?

### ISSUE THREAD

**Issue by nstdspace** [h8man/NavMeshPlus#85]
The "native" navmesh agent is a cylinder pointing "outwards" of the 2d map, i.e. in negative z direction.
Setting agent.updateRotation to false does not change that, because this is just how the navmeshagent works:

![grafik](https://user-images.githubusercontent.com/28611589/184506144-dd6e07d9-ce34-449b-8541-1e577f670c5e.png)

If the sprite is square- or circle-ish, it can be approximated by this capsule-base-face. But how would you deal with sprites of other shapes, e.g. rectangular?

![grafik](https://user-images.githubusercontent.com/28611589/184507181-d95140ac-2f1e-436c-8971-187269e0df54.png)

I'm aware of the fact that this is not a problem with navmeshplus directly, but it's related to the default workflow suggested in the wiki, I think.

**Comment by h8man** [comment]
@nstdspace , Hello.

NavMesh agent is a native to Unity and navmesh, in both senses. Agent shape cannot be changed.
Navmesh and navmesh path calculate is based on cylinder and doesn't allow custom shapes.

So cylinder is the only option for pathfinding in Unity.

You can utilize NavMesh raycast static functions to create custom pathfinding and NavMesh agent (to some extent).
https://docs.unity3d.com/ScriptReference/AI.NavMesh.Raycast.html

That's information I have.
