### ISSUE TITLE
Isometric z as y tilemap doesn't seem to bake properly

### ISSUE THREAD

**Issue by d-3nnis** [h8man/NavMeshPlus#86]
I have an isometric tilemap, with the inspector view shown. I have added the modifier component, with the walkable override.

![image](https://user-images.githubusercontent.com/38957070/184521934-aae6486b-205e-4174-a641-0e437e6d2632.png)

I have the top level navmesh game object, also shown. If I leave the default area option as walkable, it covers the entire screen. However, if I switch to not walkable, it somewhat accurately covers the tilemap. However, this also includes the sides of the blocks. That being said, I'm not sure what the fix would be for the sides of the blocks, since they are technically just sprites.

![image](https://user-images.githubusercontent.com/38957070/184521965-a16e02f3-5c2a-4ef7-88d9-bc838c3ac13f.png)

![image](https://user-images.githubusercontent.com/38957070/184521981-691a4bf7-9006-464d-aa23-af0d8371cdb8.png)

![image](https://user-images.githubusercontent.com/38957070/184522004-8cd1cd3d-962b-48b5-bada-3b3004b0d6e1.png)

**Comment by h8man** [comment]
@d-3nnis Hello,

For blocks that are extruding downward you should edit sprite shape inside a sprite and bake again. Sprite shape determine witch part is essential by adjusting "custom outline"

![image](https://user-images.githubusercontent.com/44724892/184525647-f8b279c3-8a5d-4488-bc63-0b3a57f7de87.png)

**Comment by d-3nnis** [comment]
Ok, thanks. However the issue still remains that when I try and bake the navmesh for walkable, the entire screen gets covered.

**Comment by h8man** [comment]
@d-3nnis 

I would say its design limitation. From tilemap size we get world bound box, but for isometric timemap is not rectangular. 
So if you select default as walkable area it will fill whole tilemap and some excessive area.

So either select non-walkable as default or paint out area that is not part of your tilemap.

**Comment by h8man** [comment]
did you get answers? Can I close this issue?

**Comment by d-3nnis** [comment]
Yes, thanks!
