### ISSUE TITLE
Can't bake isometric tilemap like a maze.

### ISSUE THREAD

**Issue by Dezzexx** [h8man/NavMeshPlus#88]
Hi @h8man!
Thank you very much for your project, I use your work often, but there is one problem that I cannot solve.

I want to make a TD game by implementing pathfinding for creeps to castle on multiple roads and NavMeshAgent for player units (besides buildings).

But I can't bake a maze-style grid so that creeps and units walk on the roads of the tilemap. 
If I mark the mesh as walkable and bake in the default area by marked in modifyer like  "not walkable", nav mesh data object is baked but it doesn't show up on the screen at all. 
If baked as a walkable default area, it bakes a piece of the tile map completely, but I need it exactly like in a maze.

For example, it should look something like this:
![image](https://user-images.githubusercontent.com/91484709/186754930-a307e963-c79d-4209-b19a-1379b63dd3e2.png)
but i have this 
![image](https://user-images.githubusercontent.com/91484709/186755138-63418566-7d02-4e7f-94d9-8c85528d59a1.png)
![image](https://user-images.githubusercontent.com/91484709/186755270-a0fe7101-95ba-48bd-9d1f-162582ba49b4.png)
![image](https://user-images.githubusercontent.com/91484709/186755344-d1ed889b-8978-471b-ae92-88edf866ca21.png)

I don't mark other meshes as not walkable with a modifier like in issue #76.

My unity version is 2021.3.8f1 LTS.

I thought the problem was with the sprites (Kenney) I'm using, but adding sprites from your RedHotSweetPapper project still doesn't work.
But it works in your project (I formatted your project for my version of Unity by running it separately) and everything works as it should.
I tried to recreate a project, assuming that something broke in mine, but it did not help

Help me pls C:

**Comment by Dezzexx** [comment]
P.s. PPU for sprites = 512 and grid cell size for correct display of tiles:
![image](https://user-images.githubusercontent.com/91484709/186760189-eb2cf293-1078-41d6-abbc-4d941af81861.png)

**Comment by h8man** [comment]
@Dezzexx Hello,

Your setup looks fine. So lets troubleshoot things
What logs do you have in console? Enable Inspector Debug view and check that extensions does refer parent NavMesh 
![image](https://user-images.githubusercontent.com/44724892/186868315-b1b98694-e9f1-43ca-a9c5-87196b0eb602.png)

**Comment by Dezzexx** [comment]
I removed the NavMeshCollectSource2d component and added it again like you said.

These are all the logs that appear after baking:
![image](https://user-images.githubusercontent.com/91484709/186903306-95169337-afba-4150-a0e0-6c9b11b65b3a.png)

**Comment by h8man** [comment]
I don't see any issue in your setup. Can you create test project and sent it to me?

**Comment by Dezzexx** [comment]
I will send this one, since this is a test version.
[Test.zip](https://github.com/h8man/NavMeshPlus/files/9433360/Test.zip)

**Comment by h8man** [comment]
It spend literally hours, until I found
![image](https://user-images.githubusercontent.com/44724892/187087935-821d3ab9-b844-4229-bfb2-96b1ab043aae.png)

Your map is to small or agent is too big. I would say tiles are too small, as your argent should be around 0.5 radius.

**Comment by Dezzexx** [comment]
Thank you very much, it works!
