### ISSUE TITLE
Sources 0

### ISSUE THREAD

**Issue by LuisBoyd** [h8man/NavMeshPlus#89]
It keeps saying sources are 0 when I press bake even if there are navmesh modifiers in the scene and the navmeshcollect2dsources is always asking for a navmesh surface component when I have one attached to the object already

**Comment by h8man** [comment]
@LuisBoyd Hello,

NavMeshModifier should be attached to object subjected to navmesh, while navmeshcollect2dsources should be added to the same object that have NavMeshsurface component. Refer to demo https://github.com/h8man/RedHotSweetPepper
