### ISSUE TITLE
-90 degree X rotation

### ISSUE THREAD

**Issue by 0xdeployer** [h8man/NavMeshPlus#91]
Hi. I am spawning enemies on the server using Mirror. When they render on the client the X rotation is -90 degrees. This makes them disappear. Any ideas how to stop this? Both updatRotation and updateUpAxis are set to false.

**Comment by 0xdeployer** [comment]
Actually may have fixed it by adding the drift you mentioned in the Known Issues sections of the guide.

**Comment by 0xdeployer** [comment]
Ok negative that did not fix it.

**Comment by h8man** [comment]
@0xdeployer Hello,

I made I double check on my rotations
![image](https://user-images.githubusercontent.com/44724892/194266115-fabeb4cb-4648-42ae-bbd7-384fa32a953a.png)

And they seems to be reasonable. But "Mirror" is out of my league of qualification, I have no idea what's under the hood.

Better to check how "Mirror" mirrors Agents.

**Comment by 0xdeployer** [comment]
Thanks perhaps I will open an issue with them.
