### ISSUE TITLE
Agent can't go through small gaps.

### ISSUE THREAD

**Issue by syffin** [h8man/NavMeshPlus#92]
![Screenshot (141)](https://user-images.githubusercontent.com/104688936/194732432-875b84c5-618b-4243-ba7d-0ec0cb323005.png)
How would I make the mesh stay at the same size as the collider? Right now the agent (an enemy) can't chase the player through these 1 block gaps, and instead tries to go around the whole obstacle. I'm using a tilemap collider 2d that's using a composite collider 2d. Thanks!

**Comment by h8man** [comment]
Hello @syffin

Change Agent's radius and bake again
![image](https://user-images.githubusercontent.com/44724892/194742277-59f023eb-d5c2-44e8-80d6-0c824a64e4a3.png)

**Comment by syffin** [comment]
Thanks!
