### ISSUE TITLE
NavMeshAgent collides between each other

### ISSUE THREAD

**Issue by gabriel654165** [h8man/NavMeshPlus#94]
Hello, 

I'm on a 2d game and my agents are colliding between each others.
![Screenshot from 2022-10-27 12-57-56](https://user-images.githubusercontent.com/62654705/198188102-9a5b7b64-e5bf-4a59-841a-55c02b33201f.png)

I tried to disable the physics colliding between the layers of my Objects agents but it doesn't work.

Is there a way to prevent it please ?

**Comment by h8man** [comment]
Hello @gabriel654165 

Agent collision is not physics based. You need to config your agent. Try to disable avoidance
![image](https://user-images.githubusercontent.com/44724892/198238083-4f552923-9be0-49e9-b991-dee47549180e.png)

**Comment by gabriel654165** [comment]
> Hello @gabriel654165
> 
> Agent collision is not physics based. You need to config your agent. Try to disable avoidance ![image](https://user-images.githubusercontent.com/44724892/198238083-4f552923-9be0-49e9-b991-dee47549180e.png)

Okay thank you verry much it works !
