### ISSUE TITLE
Improvement/HowTo:  Agent as Circle rater than Rectangle

### ISSUE THREAD

**Issue by marcgardent** [h8man/NavMeshPlus#95]
Hello

The NavAgent is cylinder and so in XY plan is Rectangle and in XZ is circle.
In adition, NavAgent's orientation is absolute : the parent's transform is not applied!

Primary work-arround:  change camera's direction to  XZ and it works fine the NavAgent is like circle!
But some other 2D features are buggy in XZ plan >__< (shadow-Cast in my case).

Do you have an idea to orient the NavAgent in XY plan as circle?

Thx in advance.

**Comment by h8man** [comment]
Hello @marcgardent 

Here is a demo https://github.com/h8man/RedHotSweetPepper
Wiki https://github.com/h8man/NavMeshPlus/wiki/HOW-TO#intro
The script to prevent update UP axis
	void Start()	{
		var agent = GetComponent<NavMeshAgent>();
		agent.updateRotation = false;
		agent.updateUpAxis = false;
	}

**Comment by marcgardent** [comment]
Thx for your reply @h8man,

Ok ok! 
![image](https://user-images.githubusercontent.com/5570351/199093984-1625e5b0-db54-4157-a5df-826cd6b408ca.png)

During the runtime and the baking process is OK!
My bad!

thx.
