### ISSUE TITLE
Terrain module dependency

### ISSUE THREAD

**Issue by mitay-walle** [h8man/NavMeshPlus#96]
Has unnecessery dependency to Terrain.  
![image](https://user-images.githubusercontent.com/5578552/200046916-b9cb7dd1-53b4-4fa5-aa51-ef81d778c78d.png)

You can make it optional by "Defining symbols based on Unity and project package versions".
https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html
![image](https://user-images.githubusercontent.com/5578552/200047256-a572db2c-89bd-4a36-9e52-c83e2c1d4f1a.png)

**Comment by h8man** [comment]
Thank you for feedback and PR.
