### ISSUE TITLE
I Cannot figure out why it's not baking correctly

### ISSUE THREAD

**Issue by thmsmarque** [h8man/NavMeshPlus#99]
I'm on it for 4 hours and still can't understand why. Could you?

![Capture](https://user-images.githubusercontent.com/118009503/201391166-1f473bab-bf04-4ea5-880c-8f34076b82e8.PNG)
My walls have NavMeshModifier component with Not Walkable and my floor with Walkable.
Thanks for trying

**Comment by rakhin** [comment]
I'm having the same issue but I managed to get mine to bake correctly the first time. However, if i try rebaking it or clearing the data and baking again to add in new obstacles, the navmesh breaks.

**Comment by h8man** [comment]
Hello @thmsmarque

What is the output of console? The only thing I see that navmesh has (50 ;-20), try set to (0;0)

**Comment by thmsmarque** [comment]
It's now baking correctly, thank you you were right!
